### PR TITLE
[Rust Server] Bugfix #5948 (Generated client code "Disabled because there's no example")

### LINKED ISSUE #5948: [BUG] [Rust Server] Generated client code "Disabled because there's no example"
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

#3313  I think we don't currently derive examples for models, so you'd need to define the example for the object as a whole.
-- But I add the example, also get "Disabled because there's no example" issue.
        /* Disabled because there's no example.
        Some("CreateRepo") => {
            let result = rt.block_on(client.create_repo(
                  ???
            ));
            info!("{:?} (X-Span-ID: {:?})", result, (client.context() as &dyn Has<XSpanIdString>).get().clone());
        },
        */

##### openapi-generator version

3.0.1

##### OpenAPI declaration file content or url

//modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml
  /repos:
    post:
      tags: [Repo]
      operationId: CreateRepo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ObjectParam"
            example:
              # Properties of a referenced object
              requiredParam: true
      responses:
        '200':
          description: Success

##### Command line used for generation

bin/rust-server-petstore.sh

##### Steps to reproduce

I add the test case to the followning file.
//modules/openapi-generator/src/test/resources/3_0/rust-server/openapi-v3.yaml

##### Related issues/PRs

#3313

##### Suggest a fix

Using the yaml example.

### PR DESCRIPTION
**Pull request by paladinzh**
Fix #5948 (Generated client code "Disabled because there's no example")

### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
cc @frol (2017/07) @farcaller (2017/08) @bjgill (2017/12) @richardwhiuk (2019/07)

**Comment by wing328** [comment]
@paladinzh thanks for the PR, can you please merge the latest master of https://github.com/OpenAPITools/openapi-generator into the branch to see if the CI issues are resolved?

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java [hunk 1]
```diff
@@ -1083,7 +1103,8 @@ public CodegenParameter fromRequestBody(RequestBody body, Set<String> imports, S
             // defined.
             if (codegenParameter.vendorExtensions != null && codegenParameter.vendorExtensions.containsKey("x-example")) {
                 codegenParameter.example = Json.pretty(codegenParameter.vendorExtensions.get("x-example"));
-            } else {
+            } else if (!codegenParameter.required) {
+                //mandatory parameter use the example in the yaml. if no example, it is also null.
```
Comment (richardwhiuk) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java:1107]: Can you explain this logic?

If there's an optional parameter, if it's been provided, we can still provide an example if one has been given?

Comment (paladinzh) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java:1107]: Yes. You can provide example, and all will be ok.
The issue is current example code will choose a value for the parameter. If it is optional, it will give None directly, but if required, it can only use the codegenParameter.example value.
So if we set codegenParameter.example null with required, the example will get problem in generating.

Comment (paladinzh) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustServerCodegen.java:1163]: Yes. You can provide example, and all will be ok.
The issue is current example code will choose a value for the parameter. If it is optional, it will give None directly, but if required, it can only use the codegenParameter.example value.
So if we set codegenParameter.example null with required, the example will get problem in generating.

**Comment by wing328** [comment]
If no further feedback/question from anyone, I'll merge it tomorrow.
