### PR TITLE
Fix generated go client cannot upload file

### LINKED ISSUE #8392: [BUG][Go] Generated go client cannot upload file
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue? [repo with code spec and code to reproduce](https://github.com/dhontecillas/openapi-generator-go-upload-bug)
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

Have an [OpenAPI v3 endpoint definition to upload a file](openapi.yaml), like the one provided in the [repo](https://github.com/dhontecillas/openapi-generator-go-upload-bug), when you create the client, and try to execute an upload, you get a `Invalid body type` error. (You should get a connection error or similar if the client request was sent).

## How to reproduce

The `Makefile` uses the dockerized version of the `openapi-generator-cli` tool, so first:

`docker pull openapitools:/openapi-generator-cli`

Once you have the image just run:

```
make buildclient
```

That will create a `pkg/bug` dir with the generated code, then run:

```
go run .
```

See the output has an "Invalid body type"

## Identifying the issue

Once the code is generated, we can find the **error string** comes from the file `pkg/bug/client.go`, in the function `setBody`.

```golang
func setBody(body interface{}, contentType string) (bodyBuf *bytes.Buffer, err error) {
	if bodyBuf == nil {
		bodyBuf = &bytes.Buffer{}
	}

	if reader, ok := body.(io.Reader); ok {
		_, err = bodyBuf.ReadFrom(reader)
	} else if b, ok := body.([]byte); ok {
		_, err = bodyBuf.Write(b)
	} else if s, ok := body.(string); ok {
		_, err = bodyBuf.WriteString(s)
	} else if s, ok := body.(*string); ok {
		_, err = bodyBuf.WriteString(*s)
	} else if jsonCheck.MatchString(contentType) {
		err = json.NewEncoder(bodyBuf).Encode(body)
	} else if xmlCheck.MatchString(contentType) {
		err = xml.NewEncoder(bodyBuf).Encode(body)
	}

	if err != nil {
		return nil, err
	}

	if bodyBuf.Len() == 0 {
		err = fmt.Errorf("Invalid body type %s\n", contentType)
		return nil, err
	}
	return bodyBuf, nil
}
```

The problem is not an invalid body type, but a 0 content length.

And that happens because in `pkg/bug/api_default.go` file, the function to set the Body is:

```golang
func (r ApiUploadContentRequest) Body(body *os.File) ApiUploadContentRequest {
	r.body = &body
	return r
}
```

**r.body** is not of type `*os.File` but `**os.File`, see the generated struct

```golang
type ApiUploadContentRequest struct {
	ctx _context.Context
	ApiService *DefaultApiService
	body **os.File
}
```

so, when this part of `setBody` function is executed, the `**os.File` does not implement the `io.Reader` interface, and the body is not read.

```golang

	if reader, ok := body.(io.Reader); ok {
		_, err = bodyBuf.ReadFrom(reader)
	} else if b, ok := body.([]byte); ok {
```

##### openapi-generator version

`latest`

##### OpenAPI declaration file content or url

[openapi.yaml in provided public repo](https://github.com/dhontecillas/openapi-generator-go-upload-bug/blob/master/openapi.yaml) 

##### Generation Details

Provided a [Makefile](https://github.com/dhontecillas/openapi-generator-go-upload-bug/blob/master/Makefile)

##### Steps to reproduce

Provided in the description section.

##### Related issues/PRs

No that I know

##### Suggest a fix

1. Naive one is to add an if case in the [client template](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/client.mustache#L451):

```golang
	if reader, ok := body.(io.Reader); ok {
		_, err = bodyBuf.ReadFrom(reader)
	} else if readerPtr, ok := body.(*io.Reader); ok {
		_, err = bodyBuf.ReadFrom(*readrPtr)
	} else if b, ok := body.([]byte); ok {
```

2. Change the code generation so the body filed in the
    struct becomes of type `*os.File`

```golang
type ApiUploadContentRequest struct {
	ctx _context.Context
	ApiService *DefaultApiService
	body *os.File
}
```

That might involve something related with the [AbstractGoCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java#L118) file ?

### PR DESCRIPTION
**Pull request by dhontecillas**
Fixes #8392 with the naive approach of checking if the body type is `**os.File` , so it can read its content and avoid the bug of not reading the bytes and having content-length 0.

Tested the fixed code on a separate branch in the same repo used to reproduce the issue : https://github.com/dhontecillas/openapi-generator-go-upload-bug/tree/test_fix (the updated line can be found in https://github.com/dhontecillas/openapi-generator-go-upload-bug/blob/test_fix/pkg/bug/client.go#L415 ). When running the `go run . ` command in that branch, the bug is not reproduced anymore. We get an output of : 

```
The request failed for a different reason: Post "http://127.0.0.1:8000/upload": dial tcp 127.0.0.1:8000: connect: connection refused
```
That is the expected result as we do not have any server running.

Can you have a look @antihax @grokify @kemokemo  @jirikuncar please ? thank you

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by dhontecillas** [comment]
hi @jirikuncar , I see there is a test failing for this PR, could you help me into fixing that ?

**Comment by wing328** [comment]
cc @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01)

**Review by jirikuncar — APPROVED** [review]

File: samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go [hunk 1]
```diff
@@ -367,9 +366,9 @@ func (c *APIClient) decode(v interface{}, b []byte, contentType string) (err err
 		return nil
 	}
 	if jsonCheck.MatchString(contentType) {
-		if actualObj, ok := v.(interface{GetActualInstance() interface{}}); ok { // oneOf, anyOf schemas
-			if unmarshalObj, ok := actualObj.(interface{UnmarshalJSON([]byte) error}); ok { // make sure it has UnmarshalJSON defined
-				if err = unmarshalObj.UnmarshalJSON(b); err!= nil {
+		if actualObj, ok := v.(interface{ GetActualInstance() interface{} }); ok { // oneOf, anyOf schemas
+			if unmarshalObj, ok := actualObj.(interface{ UnmarshalJSON([]byte) error }); ok { // make sure it has UnmarshalJSON defined
+				if err = unmarshalObj.UnmarshalJSON(b); err != nil {
```
Comment (wing328) [inline samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go:371]: I'll incorporate these minor code format enhancements in the template with another PR.

**Comment by wing328** [comment]
CircleCI C failure due to code format change in the sample. Will fix it after merging this in the master.

File: samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go (hunk 1 above)
Comment (wing328) [reply samples/openapi3/client/extensions/x-auth-id-alias/go-experimental/client.go:371]: Filed https://github.com/OpenAPITools/openapi-generator/pull/8715

**Comment by wing328** [comment]
@dhontecillas thanks for the PR, which has been included in the v5.1.0 release: https://twitter.com/oas_generator/status/1373636654024380423
