### PR TITLE
typescript-fetch: Escape operation-id if clashing with model names

### LINKED ISSUE #6002: [BUG][typescript-fetch] Name clash between models and operations
##### Description

Imagine a Model:

```yaml
    SubscribeRequest:
      type: object
      properties:
        # ...
```

and an operation called subscribe:

```yaml
paths:
  /subscriptions:
    post:
      summary: Subscribe
      operationId: subscribe
      parameters:
          # ...
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscribeRequest'
        required: true
```

The generated TypeScript operation would import `SubscribeRequest` but also generate a class called `SubscribeRequest` in the same file, which leads to a compilation error:

```js
import {
    SubscribeRequest,
    SubscribeRequestFromJSON,
    SubscribeRequestToJSON,
} from '../models';

// ...

// ERROR - SubscribeRequest name already taken
export interface SubscribeRequest {
    // ...
}
```

##### openapi-generator version

Today's master (but also happens with latest released version)

##### Suggest a fix

One "naive" fix would be to simply escape all models that end with `Request`:

```java
    @Override
    public String toModelName(final String name) {
        String modelName = super.toModelName(name);
        if (modelName.endsWith("Request") && !modelName.startsWith("Model")) {
            modelName = "Model" + modelName;
        }
        return modelName;
    }
```

### PR DESCRIPTION
**Pull request by haraldF**
A model import might clash with an operation when badly named. Append a "Operation" to the name to disambiguate and make the code compil.e

Closes #6002

### PR checklist

- [ X ] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ X ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ X ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [ X ] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ X ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by haraldF** [comment]
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny @topce @akehir @petejohansonxo @amakhrov review please?

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java [hunk 1]
```diff
@@ -235,9 +235,24 @@ private void addNpmPackageGeneration() {
...
     }
 
+    private void escapeOperationIds(Map<String, Object> operations) {
+        Map<String, Object> _operations = (Map<String, Object>) operations.get("operations");
+        List<CodegenOperation> operationList = (List<CodegenOperation>) _operations.get("operation");
+        for (CodegenOperation op : operationList) {
+            String param = op.operationIdCamelCase + "Request";
+            if (op.imports.contains(param)) {
+                // we import a model with the same name as the generated operation, escape it
+                op.operationIdCamelCase += "Operation";
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java:249]: @wing328 is changing the operation id a behavior a user would expect? or does a user expect the operation id to remain unaltered?

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java:249]: For example, if the operationId is a reserved word (e.g. return), the output won't work/compile so we need to escape it.

We're doing the same thing in other generators to ensure the output compiles without issues by escaping operationId, property name, parameter name and more.
