### PR TITLE
[JAVA] Manage List<Integer> datatype for enum

### LINKED ISSUE #49: [java] enum for int array initialized with strings
##### Description

The generated code for the enums of int types, in an array of said enums is initialized with a string.
Compilation fails
```java
  public enum TypeEnum {
    _0("0"),
    
    _1("1"),
    
    _2("2"),
    
    _3("3")
```
##### openapi-generator version

master

##### OpenAPI declaration file content or url

```yaml
  TypeIds:
    type: object
    properties:
      type:
        type: array
        items:
          type: integer
          format: int32
          enum:
          - 0
          - 1
          - 2
          - 3
```
##### Command line used for generation

java -jar ./openapi-generator-cli.jar generate  -i ./Api.yaml  -o ./genjava -l java

### PR DESCRIPTION
**Pull request by Zomzog**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Add method call for manage datatype List<> when creating enum value in java.

Must fix #49.

Technical committee:
@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java [hunk 1]
```diff
@@ -1036,19 +1037,34 @@ public String toEnumVarName(String value, String datatype) {
...
             return "\"" + escapeText(value) + "\"";
         }
     }
 
+    /**
+     * @param datatype
+     * @return the contained datatype if datatype is List
+     */
+    private String sanitizeForEnum(String datatype){
+        Pattern p = Pattern.compile("List<(.*)>");
```
Comment (jmini) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java]: This will not work with array of array.

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java [hunk 2]
```diff
@@ -1036,19 +1037,34 @@ public String toEnumVarName(String value, String datatype) {
 
     @Override
     public String toEnumValue(String value, String datatype) {
-        if ("Integer".equals(datatype) || "Double".equals(datatype)) {
+        String sanitzedDataType = sanitizeForEnum(datatype);
```
Comment (jmini) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java]: Who is calling this method?

I did not check it yet, I think we could add a parameter and provide the mostInnerItems type (will be added with #66)

Comment (Zomzog) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java]: The method is called into updateCodegenPropertyEnum.
I've done a second try where I search the most inner datatype on this method, so I think you're right, I can replace my call to findMostInnerDatatype method with a simple var.mostInnerItems.datatype with #66 .

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java [hunk 3]
```diff
@@ -50,6 +50,7 @@
 import java.util.List;
 import java.util.ListIterator;
 import java.util.Map;
+import java.util.regex.Matcher;
```
Comment (jmini) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java]: I think this is an unused import

**Comment by Zomzog** [comment]
I've added the missing "isInteger" to the CodegenModel, but I'm not sure it's the right solution because it adds a java enum specific requirement into a generic model.

**Comment by jmini** [comment]
> I've added the missing "isInteger" to the CodegenModel, but I'm not sure it's the right solution because it adds a java enum specific requirement into a generic model.

This is not a problem, in my opinion we should rework the Codegen classes to have more stuff in common (`CodegenModel` and `CodegenProperty`) => See #20

But I am not sure that the way you have implemented it will work. You should be aware that each language is allowed to change the value in `dataType` (it is mutable). By looking at the `CodegenModel#dataType` usage, some language are putting other values than "Integer" in that member.
I guess it would be safer to add a `isInteger` property, similar to `CodegenProperty#isInteger`. In this case, I think that you will not need a getter.

**Comment by Zomzog** [comment]
Ok, I've had it as property.

Maybe dataType must be wrap into a valueObject during #20 to simplify the model and avoid having the possibility of an Integer that respond "false" to isInteger.

**Comment by jmini** [comment]
Thank you for the changes.

I tested it with OAS3 spec mentioned in my comment, and I got several problems.

**Java client** (library `okhttp-gson` [default], `rest-assured):

```java
  public static class Adapter extends TypeAdapter<LongEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final LongEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LongEnum read(final JsonReader jsonReader) throws IOException {
      Long value = jsonReader.nextInt(); //COMPILE ERROR
      return LongEnum.fromValue(String.valueOf(value));
    }
  }
```
I did not look into the code, but maybe you will need `isLong` similar to `isInteger`.

**Server** (generator name `jaxrs-cxf-cdi`)

I got a lot of compile error for `IntEnum.java` and `LongEnum.java`. Here the file, with some comments (I did not analyze it in detail, feel free to do other changes in order for the files to compile):
```java
@XmlType(name="")
@XmlEnum(Long.class)
public enum LongEnum {

    @XmlEnumValue(20l) NUMBER_20(Long.valueOf(20l)), @XmlEnumValue(30l) NUMBER_30(Long.valueOf(30l)), @XmlEnumValue(40l) NUMBER_40(Long.valueOf(40l));


    private Long value;

    LongEnum(Long v) {
        value = v;
    }

    public String value() { //RETURN TYPE SHOULD BE 'Long'
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static LongEnum fromValue(String v) { //PARAMETER TYPE SHOULD BE 'Long'
        for (LongEnum b : LongEnum.values()) {
            if (String.valueOf(b.value).equals(v)) { //I THINK, SHOULD BE 'Long.valueOf(..)' ?

                return b;
            }
        }
        return null;
    }
}
```

**Comment by Zomzog** [comment]
Fixed for java, jaxrs-cxf-cdi and kotlin.

**Comment by jmini** [comment]
I will have a look at your changes later today. Thank you a lot.

**Comment by jmini** [comment]
@wing328, @jimschubert:

An addition on `CodegenModel` like this:

* `CodegenModel.isString`
* `CodegenModel.isInteger`

See:
https://github.com/Zomzog/openapi-generator/blob/e56a708531e375bec66c901ae41908f3192a2a9b/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java#L47

Is that allowed for a patch release (`3.0.x`) or should we contribute this to `3.1.x` because of the API change?

In my opinion it can be added, but I am not sure about the change policy.

**Comment by jimschubert** [comment]
@jmini I wouldn't consider this a breaking change unless it would cause custom templates with by users to break (as far as I can tell, that's not the case).

I do think it's weird adding Java specific code to the shared CodegenModel. When I've had to do things like this in Kotlin and C#, I've done it on those generators base types as a vendor extension. Putting it on CodegenModel means _all_ templates can consume it and making changes will be difficult.

I would recommend that to keep this change, the public fields should be getter/setters.

**Comment by wing328** [comment]
@Zomzog can you share a minimal spec to reproduce the issue? I may have a better approach to address the problem

**Comment by jmini** [comment]
@wing328 : what is wrong with the one I have published as comment in this PR: https://github.com/OpenAPITools/openapi-generator/pull/75#issuecomment-389885215

You have an enum for String (to ensure no regression), for Long and and for Integer.

---

I did not checked the last changes here, but each time I look at the changes @Zomzog is getting closer to the result.

Let me perform some tests before I can approve this PR, but the work so far looks good to me.

---

@jimschubert:

> I do think it's weird adding Java specific code to the shared CodegenModel. When I've had to do things like this in Kotlin and C#, I've done it on those generators base types as a vendor extension. Putting it on CodegenModel means all templates can consume it and making changes will be difficult.

This is not java specific at all... It is valid OAS and needs potentially to be implemented everywhere. @Zomzog did a great job by implementing:

* java
* kotlin

Other language maintainers interested in such a feature will need to pick the new exposed stuff in their templates.

---

@jimschubert: thank you for your definition of a breaking change. As this is an addition only, we will be able to merge it on `master`.

**Comment by jimschubert** [comment]
@jmini looking at the generated code, I'd consider this a breaking change as users will no longer be able to generate Kotlin code without modifying existing code.

**Comment by wing328** [comment]
@jmini thanks for the pointer. I'll use that to repeat the issue.

**Comment by jmini** [comment]
I have verified this change, I think it now works well. Thank you a lot for this contribution.

As discussed earlier here, I propose to merge it on `3.1.x`.

---

@wing328:
> I may have a better approach to address the problem

This change is well covered with unit tests, you can still improve the implementation later.

**Comment by jmini** [comment]
@Zomzog : In order to prepare the merge, I took the liberty to merge `3.1.x` on your branch `feature/49` as commit 6998a6a
