### PR TITLE
fix(rust): Add anyOf support to Rust client generator

### LINKED ISSUE #21894: [BUG] [Rust] Generator produces empty structs for anyOf schemas
## Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you tested with the latest master to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

## Description

The OpenAPI Generator for Rust produces empty structs when encountering `anyOf` schemas, making it impossible to use these types properly. This issue affects any OpenAPI specification that uses `anyOf` to define fields that can accept multiple types (e.g., a string or an enum).

While `oneOf` support was added in previous PRs (#20336, #20101), the `anyOf` construct remains unsupported and generates unusable empty structs.

## OpenAPI Generator Version

- 7.10.0
- 7.15.0  
- 7.16.0-SNAPSHOT (latest master)

## OpenAPI Specification

```yaml
openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
components:
  schemas:
    TestResponse:
      type: object
      properties:
        model:
          $ref: '#/components/schemas/ModelIdentifier'
    ModelIdentifier:
      description: Model identifier that can be a string or specific enum value
      anyOf:
        - type: string
          description: Any model name as string
        - type: string
          enum:
            - gpt-4
            - gpt-3.5-turbo
            - dall-e-3
          description: Known model enum values
```

## Steps to Reproduce

```bash
# Using Docker
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:latest generate \
    -i /local/spec.yaml \
    -g rust \
    -o /local/generated \
    --package-name test_api

# Examine the generated file
cat generated/src/models/model_identifier.rs
```

## Current Behavior (Actual Output)

The generator produces an empty struct that cannot hold any data:

```rust
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelIdentifier {
}

impl ModelIdentifier {
    pub fn new() -> ModelIdentifier {
        ModelIdentifier {
        }
    }
}
```

## Expected Behavior

The generator should produce a usable type that can handle both variants. Following the pattern used for `oneOf`, it should generate an untagged enum:

```rust
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModelIdentifier {
    String(String),
}
```

## Impact

This makes the generated client unusable for any API that uses `anyOf` schemas. Real-world examples include:

- OpenAI API: Model parameters that accept either a string or predefined model enum

## Related Issues

- #1369 - Related issue about `oneOf` not generating enums (marked as fixed, but only for `oneOf`, not `anyOf`)
- #20101 - Rust-Axum `oneOf` handling 
- #20336 - PR that fixed `oneOf` support for Rust client

## Proposed Solution

The `anyOf` construct should be handled similarly to how `oneOf` is currently handled in the Rust generator. Since Rust's serde untagged enum will deserialize to the first matching variant, this approach works well for `anyOf` semantics where one or more schemas must match.

The fix would involve extending the existing `oneOf` logic in `RustClientCodegen.java` to also process `anyOf` schemas, generating the same untagged enum structure.

## Workaround

Currently, users must either:

1. Modify the OpenAPI spec to change `anyOf` to `oneOf` before generation
2. Post-process the generated code to replace empty structs with proper types
3. Use `serde_json::Value` and lose all type safety

## Suggest a fix

I have a PR ready that extends the existing `oneOf` implementation to handle `anyOf` schemas in the same way, which resolves this issue.

### PR DESCRIPTION
**Pull request by timvw**
## Summary
Fixes #21894 - Add support for `anyOf` schemas in the Rust client generator by treating them similarly to `oneOf` schemas when no discriminator is present.

### Initial Implementation
- Modified `RustClientCodegen.java` to process `anyOf` schemas similar to `oneOf`
- Fixed template closing tag issue in `model.mustache` that prevented anyOf schemas from generating enums
- Added comprehensive test case `testAnyOfSupport()` to verify the fix

### Template Formatting Fix
- Maintained multi-line formatting for `#[serde(untagged)]` attribute (separate line from `pub enum`)
- Updated test assertions to use two separate checks for better consistency with codebase patterns
- Ensures generated Rust code maintains consistent formatting with existing samples

## Technical Details

The Rust generator already converts `anyOf` to `oneOf` internally for processing, but the template wasn't correctly handling these converted schemas. Now `anyOf` schemas generate proper untagged enums, matching the expected behavior for `oneOf` schemas without discriminators.

### Example Transformation

**Before (generated empty struct):**
```rust
pub struct ModelIdentifier {}
```

**After (generates untagged enum):**
```rust
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ModelIdentifier {
    String(String)
}
```

## Testing
- Added unit test `testAnyOfSupport()` that verifies anyOf schemas generate untagged enums
- Test includes verification that empty structs are not generated
- All existing Rust generator tests pass
- Samples regenerated and verified

## Note
This leverages Rust's serde untagged enum deserialization to handle anyOf schemas, which will attempt to deserialize into each variant in order until one succeeds.

PR checklist:
- [x] Read the contribution guidelines
- [x] Pull Request title clearly describes the work
- [x] Added tests to verify the fix
- [x] Verified all Rust tests pass
- [x] Samples are up-to-date

### CODE REVIEW

**Comment by wing328** [comment]
thanks for the PR

cc @frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10) @dsteeley (2025/07)

**Comment by wing328** [comment]
please review the test failure when you've time

**Comment by timvw** [comment]
I've fixed the anyOf support issue for the Rust generator. The problem was in the Mustache template and a test utility method.

## Changes made:

### 1. Fixed template closing tag (model.mustache)
The template had an incorrect closing tag `{{/composedSchemas.oneOf}}` at line 262 which should have been `{{/composedSchemas}}`. This was causing the template logic to skip to the wrong section and generate empty structs instead of enums for anyOf schemas.

### 2. Formatting adjustment (model.mustache)
Put `#[serde(untagged)]` and `pub enum` on the same line to match test expectations after linearization.

### 3. Fixed TestUtils.linearize() method
The linearize method was incorrectly replacing spaces with literal '\s' string instead of a space character, causing test assertions to fail.

## Result:
- The `testAnyOfSupport` test now passes
- anyOf schemas now correctly generate untagged enums in Rust
- All 10 Rust generator tests pass successfully

The fix leverages the existing logic in RustClientCodegen that converts anyOf to oneOf for processing. The template now properly handles these converted schemas to generate the expected untagged enum output.

The changes are available in the branch `fix/rust-anyof-support` at https://github.com/timvw/openapi-generator/tree/fix/rust-anyof-support

**Comment by timvw** [comment]
@wing328 I've reviewed the CircleCI failure. All tests pass locally on my machine:

- All 10 RustClientCodegenTest tests pass including the new testAnyOfSupport
- All 25 Rust-related tests pass (AbstractRustCodegenTest, RustAxumServerCodegenTest, RustClientCodegenTest)
- Full test suite in modules/openapi-generator passes with 3479 tests, 0 failures

The CircleCI node1 failure appears to be unrelated to the Rust anyOf changes. Could this be a flaky test or infrastructure issue? The changes are limited to:
1. The Rust model.mustache template (fixing composedSchemas closing tag)
2. TestUtils.linearize() method (fixing space replacement bug)

Both changes are isolated and shouldn't affect other generators or tests. Would you like me to investigate further or could you re-run the CircleCI build?

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java [hunk 1]
```diff
@@ -307,6 +307,69 @@ public CodegenModel fromModel(String name, Schema model) {
             mdl.getComposedSchemas().setOneOf(newOneOfs);
         }
 
+        // Handle anyOf schemas similarly to oneOf
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java:310]: thanks for the PR

would it be the same if we simply do it in the openapi normalizer instead to rename anyOf schemas to oneOf schemas?

Comment (timvw) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java:310]: No, because most languages keep anyOf and oneOf separate because they have different semantics:
  - oneOf: Exactly one schema must validate (XOR)
  - anyOf: One or more schemas must validate (OR)

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java:310]: 👌

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java [hunk 2]
```diff
@@ -307,6 +307,69 @@ public CodegenModel fromModel(String name, Schema model) {
...
+                else {
+                    // In-placed type (primitive), because there is no mapping or ref for it.
+                    // use camelized `title` if present, otherwise use `type`
+                    String anyOfName = Optional.ofNullable(schema.getTitle()).orElseGet(schema::getType);
+                    anyOf.setName(toModelName(anyOfName));
+                }
+            }
+
+            // Set anyOf as oneOf for template processing since we want the same output
+            mdl.getComposedSchemas().setOneOf(newAnyOfs);
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RustClientCodegen.java:370]: this is an "interesting approach" as it tries to "reuse" oneOf for anyOf.

it may cause confusion to the end users reviewing the mustache templates (and they won't find any `anyOf` mustache tags) but I think we can give it a try to start with

cc 
@frol (2017/07) @farcaller (2017/08) @richardwhiuk (2019/07) @paladinzh (2020/05) @jacob-pro (2022/10) @dsteeley (2025/07)

**Comment by wing328** [comment]
let's give it a try 

i'll add more tests later

**Comment by timvw** [comment]
I will see what a refactoring to proper support for anyOf (instead of piggy-backing on oneOf) would look like.

**Comment by wing328** [comment]
@timvw i just added a test but failed: https://github.com/OpenAPITools/openapi-generator/actions/runs/17515352250/job/49752143497?pr=21911

can you please take a look when you've time?

ref: https://github.com/OpenAPITools/openapi-generator/pull/21911

**Comment by timvw** [comment]
A bit busy the coming days, but I will try to follow up later this week.. 

Here are some thoughts/tests on true support for anyOf (and some extra tests for oneOf as well)... : https://github.com/timvw/openapi-generator/tree/refactoring/rust-true-anyof-support

**Comment by wing328** [comment]
please take your time

if we can't come up with a fix before the upcoming release, we will revert the change for the time being.

**Comment by wing328** [comment]
>  Add support for anyOf schemas in the Rust client generator by treating them similarly to oneOf schemas when no discriminator is present.

I like your original idea but if you want to come up with a better implementation, that's also good too.

**Comment by timvw** [comment]
> please take your time
> 
> if we can't come up with a fix before the upcoming release, we will revert the change for the time being.

That's the more re-assuring/relaxing way to proceed with this issue :)

Let's take some time to design/explore (and iterate) on this instead of rushing someting out.

**Comment by wing328** [comment]
> please take your time
> 
> if we can't come up with a fix before the upcoming release, we will revert the change for the time being.

reverted via https://github.com/OpenAPITools/openapi-generator/pull/22038
