### PR TITLE
[Java] Remove bean validation annotations on builder

### LINKED ISSUE #19188: [BUG] @Valid TYPE_USE bean validation annotation on builder causes issues on JBoss EAP 7.4
##### Description

Similar to https://github.com/OpenAPITools/openapi-generator/issues/17875. The applied fix does not entirely solve the issue.

Related to #17874, the `@Valid` bean validation annotation also gets added on TYPE_USE in the builder.

```java
  public static PartnersRestBuilder<?, ?> builder() {
    return new PartnersRestBuilderImpl();
  }

  private static class PartnersRestBuilderImpl extends PartnersRestBuilder<PartnersRest, PartnersRestBuilderImpl> {

    @Override
    protected PartnersRestBuilderImpl self() {
      return this;
    }

    @Override
    public PartnersRest build() {
      return new PartnersRest(this);
    }
  }

  public static abstract class PartnersRestBuilder<C extends PartnersRest, B extends PartnersRestBuilder<C, B>>  {
    private List<@Valid PartnerRest> items = new ArrayList<>();
    private Integer total;
    protected abstract B self();

    public abstract C build();

    public B items(List<@Valid PartnerRest> items) {
      this.items = items;
      return self();
    }
    public B total(Integer total) {
      this.total = total;
      return self();
    }
  }
}
```

<details>
<summary>PartnersRest.java</summary>

```java
package be.fgov.kszbcss.tad.admin.rest.model;

import be.fgov.kszbcss.tad.admin.rest.model.PartnerRest;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonTypeName;



@JsonTypeName("Partners")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJAXRSSpecServerCodegen", date = "2024-07-17T13:55:57.807731525+02:00[Europe/Brussels]", comments = "Generator version: 7.7.0")
public class PartnersRest  implements Serializable {
  private @Valid List<@Valid PartnerRest> items = new ArrayList<>();
  private Integer total;

  protected PartnersRest(PartnersRestBuilder<?, ?> b) {
    this.items = b.items;
    this.total = b.total;
  }

  public PartnersRest() {
  }

  /**
   **/
  public PartnersRest items(List<@Valid PartnerRest> items) {
    this.items = items;
    return this;
  }

  
  @JsonProperty("items")
  @NotNull @Valid public List<@Valid PartnerRest> getItems() {
    return items;
  }

  @JsonProperty("items")
  public void setItems(List<@Valid PartnerRest> items) {
    this.items = items;
  }

  public PartnersRest addItemsItem(PartnerRest itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }

    this.items.add(itemsItem);
    return this;
  }

  public PartnersRest removeItemsItem(PartnerRest itemsItem) {
    if (itemsItem != null && this.items != null) {
      this.items.remove(itemsItem);
    }

    return this;
  }
  /**
   **/
  public PartnersRest total(Integer total) {
    this.total = total;
    return this;
  }

  
  @JsonProperty("total")
  public Integer getTotal() {
    return total;
  }

  @JsonProperty("total")
  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartnersRest partners = (PartnersRest) o;
    return Objects.equals(this.items, partners.items) &&
        Objects.equals(this.total, partners.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartnersRest {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static PartnersRestBuilder<?, ?> builder() {
    return new PartnersRestBuilderImpl();
  }

  private static class PartnersRestBuilderImpl extends PartnersRestBuilder<PartnersRest, PartnersRestBuilderImpl> {

    @Override
    protected PartnersRestBuilderImpl self() {
      return this;
    }

    @Override
    public PartnersRest build() {
      return new PartnersRest(this);
    }
  }

  public static abstract class PartnersRestBuilder<C extends PartnersRest, B extends PartnersRestBuilder<C, B>>  {
    private List<@Valid PartnerRest> items = new ArrayList<>();
    private Integer total;
    protected abstract B self();

    public abstract C build();

    public B items(List<@Valid PartnerRest> items) {
      this.items = items;
      return self();
    }
    public B total(Integer total) {
      this.total = total;
      return self();
    }
  }
}
```
</details>

This somehow causes an issue on JBoss EAP 7.4.

I guess the presence of the `@Valid` annotation causes the container to treat the builder as a CDI bean?

Before https://github.com/OpenAPITools/openapi-generator/pull/18724:

```
org.jboss.weld.exceptions.DeploymentException: WELD-001503: Bean class which has interceptors cannot be declared final:  class be.fgov.kszbcss.tad.admin.rest.model.PartnersRest$PartnersRestBuilderImpl
```

After https://github.com/OpenAPITools/openapi-generator/pull/18724 (which attempted to fix the issue by making the builder class non-final):

```
org.jboss.weld.exceptions.DeploymentException: WELD-001436: Type be.fgov.kszbcss.tad.admin.rest.model.PartnersRest$PartnersRestBuilderImpl is not proxyable because it has a private constructor [EnhancedAnnotatedConstructorImpl] private be.fgov.kszbcss.tad.admin.rest.model.PartnersRest$PartnersRestBuilderImpl() - class be.fgov.kszbcss.tad.admin.rest.model.PartnersRest$PartnersRestBuilderImpl.""
```

##### openapi-generator version

OK in 7.1.0, broken from 7.2.0 onward.

### PR DESCRIPTION
**Pull request by jpraet**
Fixes #19188 and reverts #18724.

Generated builder classes should not contain bean validation annotations.
They are unnecessary and cause problems on some Java EE servers (e.g. JBoss EAP). 

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

 * Java: @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala  (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)  @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @martin-mfg  (2023/08)
 * Java Spring: @cachescrubber (2022/02) @welshm (2022/02) @MelleD  (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02)  @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09) @martin-mfg  (2023/08)

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java [hunk 1]
```diff
@@ -54,6 +54,8 @@ public class CodegenProperty implements Cloneable, IJsonSchemaValidationProperti
     @Getter @Setter
     public String datatypeWithEnum;
     @Getter @Setter
+    public String rawDatatypeWithEnum;
```
Comment (martin-mfg) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenProperty.java:57]: Instead of introducing a new field here, could you please define a new lambda (e.g. "removeAnnotations") in `AbstractJavaCodegen`? Similar to this: https://github.com/OpenAPITools/openapi-generator/blob/d29196a1f0ad41fc17f5d4875650f87480d66a40/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L653 You should then be able to use it like this in the mustache templates: `{{#removeAnnotations}}{{{datatypeWithEnum}}}{{/removeAnnotations}}`.
Using a lambda instead of a field eliminates the risk that future contributors make changes to `datatypeWithEnum` without keeping `rawDatatypeWithEnum` in sync.

**Review by martin-mfg — CHANGES_REQUESTED** [review]
Hi @jpraet, thanks for the PR!
Did you test locally if your changes fix the errors you reported and allow you to successfully run the generated code in JBoss EAP 7.4?

**Comment by jpraet** [comment]
> Hi @jpraet, thanks for the PR! Did you test locally if your changes fix the errors you reported and allow you to successfully run the generated code in JBoss EAP 7.4?

Yes I tested the changes locally. I will apply your suggested refactoring and test again.

**Review by martin-mfg — APPROVED** [review]

**Comment by wing328** [comment]
@jpraet let me review and merge if no question/feedback from me

have a nice weekend

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java [hunk 2]
```diff
@@ -1802,18 +1805,16 @@ public void postProcessResponseWithProperty(CodegenResponse response, CodegenPro
...
-            response.dataType = removeAnnotations(response.dataType);
-        }
+        // the response data types should not contain bean validation annotations.
+        property.dataType = removeAnnotations(property.dataType);
+        response.dataType = removeAnnotations(response.dataType);
     }
 
-    private String removeAnnotations(String type) {
-        return type.replaceAll("(?:(?i)@[a-z0-9]*+([(].*[)]|\\s*))*+", "");
+    private String removeAnnotations(String dataType) {
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java:1813]: @jpraet thanks for the PR.

the only suggestion I've is adding s docstring explaining what this function does with an example or 2 before and after applying this function (essentially explaining what the regular express does)?

Comment (jpraet) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java]: added
