### PR TITLE
[Typescript AngularJS] fix Extra package prefix in api parameters operations

### LINKED ISSUE #189: Extra package prefix created for Typescript AngularJS
##### Description

When OpenAPI generated [PetApi.ts](https://github.com/OpenAPITools/openapi-generator/blob/0373b74a758e722fa553898523aab4402138bb6e/samples/client/petstore/typescript-angularjs/api/PetApi.ts#L34) at 0373b74a758e722fa553898523aab4402138bb6e, the output correctly had the signature:

`    public addPet (pet: models.Pet, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {`

When the file was regenerated at 059a3efe467d52345f9215d79399588cbe1d5693, it now has the signature of

`    public addPet (pet: models.models.Pet, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {`

as you can see in [PetApi.ts](https://github.com/OpenAPITools/openapi-generator/blob/059a3efe467d52345f9215d79399588cbe1d5693/samples/client/petstore/typescript-angularjs/api/PetApi.ts#L34)

##### openapi-generator version

https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/3.0.0-SNAPSHOT/openapi-generator-cli-3.0.0-20180529.071922-102.jar

##### OpenAPI declaration file content or url

This is from the OpenAPI sample declaration.

##### Command line used for generation

The ones in the .pom file.

##### Steps to reproduce

1. Build OpenAPI
2. Build the samples
3. Notice that the path is incorrect and that it doesn't compile through the TS compiler.

##### Related issues/PRs

I looked but didn't see one. If I'm incorrect, please feel free to close this issue.

##### Suggest a fix/enhancement

I think this could be found by doing a bisection from the two provided commits and then mvn build'ing them and grepping for `\.models\.models` which would find it.

Additionally you might consider adding a test that regenerates the sample files and does a diff against what is checked in failing if there is a diff. This would ensure that the checked in files reflect the new reality of the generated code. Additionally, this would give you a nice diff every time someone did something that changed the generated code. Just a thought.

PS: Congrats on your progress post fork :fireworks: :champagne:. Things seem to really be coming along! I can't wait for a V3 release!

### PR DESCRIPTION
**Pull request by karismann**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10)

### Description of the PR

fix Extra package prefix in api parameters operations (fix #189)
add angularjs in ensure-up-to-date script

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularJsClientCodegen.java [hunk 1]
```diff
@@ -74,7 +74,7 @@ public String getTypeDeclaration(String name) {
     @Override
     public void postProcessParameter(CodegenParameter parameter) {
         super.postProcessParameter(parameter);
-        parameter.dataType = addModelPrefix(parameter.dataType);
+        // parameter.dataType = addModelPrefix(parameter.dataType);
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularJsClientCodegen.java]: I'll remove that (commented code) later with another PR when I've time
