### PR TITLE
[C++]Enable forward declaration for C++

### LINKED ISSUE #6377: [BUG][C++][QT5] Code not compileable when circular scheme dependencies exist
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The generated C++ (QT5) code cannot be compiled, when circular scheme dependencies are used.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```json
openapi: 3.0.0
info:
  version: 0.0.1
  title: Test
paths:
  /endpoint:
    get:
      operationId: getOptions
      description: "-"
      parameters:
      - name: OptionA
        in: header
        schema:
          $ref: '#/components/schemas/OptionA'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OptionA'
components:
  schemas:
    OptionA:
      type: object
      description: 'OptionA'
      properties:
        suboptions:
          type: array
          description: 'Suboptions of OptionA'
          items:
            $ref: '#/components/schemas/OptionB'
    OptionB:
      type: object
      description: 'OptionB'
      properties:
        suboptions1:
          type: array
          description: 'Suboptions 1 of OptionB'
          items:
            $ref: '#/components/schemas/OptionA'
        suboptions2:
          type: array
          description: 'Suboptions 2 of OptionB'
          items:
            $ref: '#/components/schemas/OptionB'
```

##### Command line used for generation
`java -cp openapi-generator-cli-4.3.1.jar org.openapitools.codegen.OpenAPIGenerator generate -i ${SPEC_FILE} -g cpp-qt5-client -o gen/ --model-name-prefix Test`

##### Steps to reproduce

1. Generate CPP code with above command line.
2. Generate Makefiles e.g. with (MAC and QT5.14.0): `cmake CMakeLists.txt -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.14.0/`
4. Compile: `make`

##### Related issues/PRs
Few similar issues (other languages) seems to exist.

##### Suggest a fix
Partly it can probably be fixed by forward declaration in headers, but not completely. More investigation needed.

### PR DESCRIPTION
**Pull request by etherealjoy**
Fixes #6377
@muttleyxd @MartinDelille @stkrwork @ravinikam 
@wing328 

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

**Fixes this spec below**
```yaml
openapi: 3.0.0
info:
  version: 0.0.1
  title: Test
paths:
  /endpoint:
    get:
      operationId: getOptions
      description: "-"
      parameters:
      - name: OptionA
        in: header
        schema:
          $ref: '#/components/schemas/OptionA'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OptionA'
components:
  schemas:
    OptionA:
      type: object
      description: 'OptionA'
      properties:
        suboptions:
          type: array
          description: 'Suboptions of OptionA'
          items:
            $ref: '#/components/schemas/OptionB'
    OptionB:
      type: object
      description: 'OptionB'
      properties:
        suboptions1:
          type: array
          description: 'Suboptions 1 of OptionB'
          items:
            $ref: '#/components/schemas/OptionA'
        suboptions2:
          type: array
          description: 'Suboptions 2 of OptionB'
          items:
            $ref: '#/components/schemas/OptionB'
```

**This spec below cannot be fixed due to C++ limitations.**

```yaml
openapi: 3.0.0
info:
  version: 0.0.1
  title: Test
paths:
  /endpoint:
    get:
      operationId: getOptions
      description: "-"
      parameters:
      - name: OptionA
        in: header
        schema:
          $ref: '#/components/schemas/OptionA'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OptionA'
components:
  schemas:
    OptionA:
      type: object
      description: 'OptionA'
      properties:
        suboptions:
          $ref: '#/components/schemas/OptionB'
    OptionB:
      type: object
      description: 'OptionB'
      properties:
        suboptions1:
          $ref: '#/components/schemas/OptionA'
```
**Generated code below has forward declaration and include as well.**
```C++
#ifndef OAIOptionB_H
#define OAIOptionB_H

#include <QJsonObject>

#include "OAIOptionA.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIOptionA;

class OAIOptionB : public OAIObject {
public:
    OAIOptionB();
    OAIOptionB(QString json);
    ~OAIOptionB() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIOptionA getSuboptions1() const;
    void setSuboptions1(const OAIOptionA &suboptions1);
    bool is_suboptions1_Set() const;
    bool is_suboptions1_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIOptionA suboptions1;
    bool m_suboptions1_isSet;
    bool m_suboptions1_isValid;
};

} // namespace OpenAPI
```
**Error for the one above**
```shell
OAIOptionB.h:53: error: field ‘suboptions1’ has incomplete type ‘OpenAPI::OAIOptionA’
   53 |     OAIOptionA suboptions1;
      |                ^~~~~~~~~~~
```

### CODE REVIEW

**Comment by etherealjoy** [comment]
@wing328 
When you have time could you please take a look at the logic for parsing the model which could have class members that reference back to the parent class?

**Comment by etherealjoy** [comment]
Other generators (like `cpp-restsdk`) however, which uses `std::shared_ptr` to instantiate class members will not be impacted, and can fully support forward declaration for circular references

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java [hunk 1]
```diff
@@ -353,4 +357,47 @@ public void preprocessOpenAPI(OpenAPI openAPI) {
...
+        }
+        return models;
+    }
+
+    private void addForwardDeclarations(CodegenModel model, Map<String, Object> objs) {
+        List<String> forwardDeclarations = new ArrayList<String>();
+        if(!model.hasVars) {
+            return;
+        }
+        for(CodegenProperty property : model.vars){
```
Comment (muttleyxd) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java:376]: I don't do much Java, but this loop looks odd, too much indentation levels IMO.

Half-assed attempt at fixing this a little - but I went down to 4 indentation levels.
I simply inverted the if statements, so they could probably be written in a smarter way.
```
for (CodegenProperty property : model.vars) {
	if (!(property.isContainer && property.mostInnerItems.isModel) && !(property.isModel))
		continue;
	
	String innerPropertyType = property.isContainer ? property.mostInnerItems.baseType : property.baseType;
	for (final Entry<String, Object> mo : objs.entrySet()) {
		CodegenModel innerModel = ModelUtils.getModelByName(mo.getKey(), objs);
		if (!(innerPropertyType.equals(innerModel.classname) && !innerPropertyType.equals(model.classname) && innerModel.hasVars))
			continue;
		for (CodegenProperty p : innerModel.vars) {
			if (!((p.isModel && p.dataType.equals(model.classname)) || (p.isContainer && p.mostInnerItems.baseType.equals(model.classname))))
				continue;
			String forwardDecl = "class " + innerModel.classname + ";";
			if (!forwardDeclarations.contains(forwardDecl)) {
				forwardDeclarations.add(forwardDecl);
			}
		}
	}
}
```

Comment (etherealjoy) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java:376]: I could make this readable like you suggested.
Need some feedback on the logic first too though.

Comment (etherealjoy) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractCppCodegen.java]: I refactored it a bit.
