### PR TITLE
[dart][core] Fix reservedWordsMappings

### LINKED ISSUE #12336: [REQ] Define custom reserved words
There are some words that should be reserved in my project using `dart-dio-next` that are not. Namely `Type` type, and `toString` field, along with `update` field that conflicts with BuiltValue classes

It would be nice if we could pass our own reserved words as needed

### PR DESCRIPTION
**Pull request by kuhnroyal**
* fixes #12336
* [core] Fix naming of reservedWordsMappings 
	* `GeneratorSettings` used a wrong name (missing `s`) which resulted in config loaded from YAMl files not working 
* [dart] Respect reservedWordsMappings when checking for reserved words

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

CC @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08) - please give your opinion on the linked issue

### CODE REVIEW

File: modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java [hunk 1]
```diff
@@ -52,7 +52,7 @@ public final class GeneratorSettings implements Serializable {
     private final Map<String, String> importMappings;
     private final Map<String, String> inlineSchemaNameMappings;
     private final Set<String> languageSpecificPrimitives;
-    private final Map<String, String> reservedWordMappings;
+    private final Map<String, String> reservedWordsMappings;
```
Comment (agilob) [inline modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: I have a feeling this might break other PRs that are in progress and use this variable or getter

Comment (kuhnroyal) [reply modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: Well that needs to be solved in whatever PR is merged last :)

Comment (agilob) [reply modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: this is a change in public API of openapi-generator. this will also break external forks of openapi generators that a lot of companies manage on their own, it's not really dart related

Comment (kuhnroyal) [reply modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: Not sure. According to the Docs, this is what it should be named like and what the CLI arg is named like.
This just brings the parser for YAML config in line.
See https://openapi-generator.tech/docs/usage/

Comment (kuhnroyal) [reply modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: Imho this is a bug and not matching the docs.

Comment (wing328) [reply modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: What about updating the doc instead?

Comment (kuhnroyal) [reply modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: @wing328 The `[--reserved-words-mappings <reserved word mappings>...]` works correct for CLI args, just not for YAML-file configuration because of the typo. There is no separate documentation for the config file, so I think it should be fixed to match.

Comment (wing328) [reply modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/GeneratorSettings.java:55]: ok. let's go with this fix. Thanks for the PR as always
