### PR TITLE
[elixir] Properly map AnyType

### LINKED ISSUE #14070: Elixir generator `AnyType` support
##### Description
When compiling spec files which contain `AnyType`, the elixir generator expects a `:struct` type to be used in `decoder.ex`.

The generated code fails because  no type `<PKG>.Model.AnyType` exists

Example Generated code found [here](https://github.com/ory/sdk/blob/847fa4451dd67b624a2820402e92ec6385128921/clients/hydra/elixir/lib/ory/model/o_auth2_client.ex#L112-L113):
```elixir
defimpl Poison.Decoder, for: Ory.Model.OAuth2Client do
  import Ory.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:jwks, :struct, Ory.Model.AnyType, options)
    |> deserialize(:metadata, :struct, Ory.Model.AnyType, options)
  end
end
```

##### openapi-generator version
`6.0.3` to latest in `main` branch

##### Related issues/PRs

The proposed fix will reference this issue and builds on the latest work by @halostatue.

* #12731 
* #12775

I  also include the related elixir issues from #12731.

* #12484
* #4011
Still there is no elixir test suite
*  #8804
* #12268

##### Suggest a fix/enhancement

When work on my branch is finished I intend to submit a PR

### PR DESCRIPTION
**Pull request by mrmstn**
Fixes #14070

This PR will handle `AnyType` as primitives to prevent the generator from generating specific classes, since in elixir structs cannot have any extra undefined files. This will also result in `AnyType` parameters not be serialized in any other way than Poison interprets it.

Since the Pet Store doesn't have some good examples to see the results of this change, here's a Dummy Spec:
```yaml
openapi: 3.0.3
info:
  title: Dummy Spec
  version: 1.0.11
servers:
  - url: https://dummy.example.com/api
paths:
  /quotas:
    get:
      operationId: GetQuotas
      responses:
        "200":
          $ref: '#/components/responses/GetQuotasResponse'
      tags:
      - Enterprise
  /dummy:
    get:
      operationId: GetQuotas
      responses:
        "200":
          $ref: '#/components/responses/GetJobScaleStatusResponse'
      tags:
      - Enterprise
components:
  schemas:
    ConsulGateway:
      properties:
        Mesh: {}
      type: object
  responses:
    GetJobScaleStatusResponse:
      description: ""
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConsulGateway'
    GetQuotasResponse:
      content:
        application/json:
          schema:
            items: {}
            type: array
      description: ""
```

The Spec contains two interesting parts. First, there is the `ConsulGateway` with the `Mesh` properties, with no further definition. 
Secondly, there is the `GetQuotasResponse` with an array of `AnyType` objects.

```diff
--- a/lib/nomad_client/api/enterprise.ex
+++ b/lib/nomad_client/api/enterprise.ex
@@ -21,7 +21,7 @@ defmodule NomadClient.Api.Enterprise do
   - `{:ok, [%AnyType{}, ...]}` on success
   - `{:error, Tesla.Env.t}` on failure
   """
-  @spec get_quotas(Tesla.Env.client, keyword()) :: {:ok, list(NomadClient.Model.AnyType.t)} | {:error, Tesla.Env.t}
+  @spec get_quotas(Tesla.Env.client, keyword()) :: {:ok, list(any())} | {:error, Tesla.Env.t}
   def get_quotas(connection, _opts \\ []) do
     request =
       %{}
@@ -32,7 +32,7 @@ defmodule NomadClient.Api.Enterprise do
     connection
     |> Connection.request(request)
     |> evaluate_response([
-      {200, [%NomadClient.Model.AnyType{}]}
+      {200, []}
     ])
   end
```

As you can see in the upper diff. The generator won't interpret the undefined list as  `%NomadClient.Model.AnyType{}` anymore, but uses `[]` instead.

```diff
--- a/lib/nomad_client/model/consul_gateway.ex
+++ b/lib/nomad_client/model/consul_gateway.ex
@@ -12,15 +12,13 @@ defmodule NomadClient.Model.ConsulGateway do
   ]
 
   @type t :: %__MODULE__{
-    :Mesh => AnyType | nil
+    :Mesh => any() | nil
   }
 end
 
 defimpl Poison.Decoder, for: NomadClient.Model.ConsulGateway do
-  import NomadClient.Deserializer
-  def decode(value, options) do
+  def decode(value, _options) do
     value
-    |> deserialize(:Mesh, :struct, NomadClient.Model.AnyType, options)
   end
 end
```

In the upper diff, you can see that `Mesh` will not be decoded to the not existing `NomadClient.Model.AnyType` anymore. `Mesh` will not be serialized to a struct and will be left as is from Poison

@halostatue or @wing328 I would be honored if you could review my changes.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java [hunk 1]
```diff
@@ -665,6 +672,10 @@ public String decodedStruct() {
             } else if (isArray && languageSpecificPrimitives().contains(baseType)) {
                 return "[]";
             }
+
+            if (this.baseType.equals("AnyType")){
+                return "%{}";
```
Comment (halostatue) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java:677]: Why are we returning an empty map here? It doesn’t look *wrong*, just *odd*.

**Review by halostatue — APPROVED** [review]
Overall this looks good, although it would be nice to see tests in PetStore, although that would require changes in far more than just here.

Many of the `python` clients appear to have multiple configurations that can be tested, some of which *appear* to have `AnyType` values in them:

```
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
inputSpec: modules/openapi-generator/src/test/resources/2_0/python-prior/petstore-with-fake-endpoints-models-for-testing.yaml
inputSpec: modules/openapi-generator/src/test/resources/3_0/extensions/x-auth-id-alias.yaml
inputSpec: modules/openapi-generator/src/test/resources/3_0/features/dynamic-servers.yaml
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
inputSpec: modules/openapi-generator/src/test/resources/3_0/python-prior/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
inputSpec: modules/openapi-generator/src/test/resources/3_0/unit_test_spec/3_0_3_unit_test_spec.yaml
```

Elixir only has one configuration file that uses

```
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
```

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java (hunk 1 above)
Comment (mrmstn) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java:677]: You're absolutely right, this line is unnecessary since the if/else check above will already handle `AnyType` (since it's now marked as primitive) and this check will never be reached for AnyType. Nice catch :D!

**Comment by mrmstn** [comment]
> Overall this looks good, although it would be nice to see tests in PetStore, although that would require changes in far more than just here.
> 
> Many of the `python` clients appear to have multiple configurations that can be tested, some of which _appear_ to have `AnyType` values in them:
> 
> ```
> inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
> inputSpec: modules/openapi-generator/src/test/resources/2_0/petstore.yaml
> inputSpec: modules/openapi-generator/src/test/resources/2_0/python-prior/petstore-with-fake-endpoints-models-for-testing.yaml
> inputSpec: modules/openapi-generator/src/test/resources/3_0/extensions/x-auth-id-alias.yaml
> inputSpec: modules/openapi-generator/src/test/resources/3_0/features/dynamic-servers.yaml
> inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
> inputSpec: modules/openapi-generator/src/test/resources/3_0/python-prior/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
> inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml
> inputSpec: modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing.yaml
> inputSpec: modules/openapi-generator/src/test/resources/3_0/unit_test_spec/3_0_3_unit_test_spec.yaml
> ```
> 
> Elixir only has one configuration file that uses
> 
> ```
> inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
> ```

Great idea! I tried to generate the client against `petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml` (same one as `python.yaml`). Sadly, this result can't be compiled since there are some issues with special variable names and their usage as path variables (DISCLAIMER: I didn't look much into the actual source of the uncompilable client)
