### PR TITLE
Avoid using Properties.clone() which is broken in Gradle

### LINKED ISSUE #7601: [BUG] Use of GlobalSettings in gradle-plugin leads to race conditions in Gradle 6.6+
##### Description

On the latest version of Gradle 6.6 and latest generator 4.3.1 I am seeing inconsistent generation of outputs, some projects where model generation is disabled, intermittently models appear and the next run they do not appear. I believe this is due to running my multi-module gradle project with a number of openapi generator tasks running at once, the current problem is with ~5 concurrent generations running.

It appears that there is a race condition in the GeneratorTask and the use of a global singleton GlobalSettings:

https://github.com/OpenAPITools/openapi-generator/blob/61b543f03dc546386467c9a7afe8864f6f609ed1/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt#L513

GlobalSettings appears to defend against this via a ThreadLocal map which seems to work in Gradle 6.5, but fail in Gradle 6.6+. I'm not sure whats changed in Gradle land but it seems like any settings configured via GlobalSettings conflict/collide with each other when running concurrently, if I set `--max-workers 1` everything works as expected, if workers is > 1 then the problems start.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

n/a

##### Generation Details

n/a

##### Steps to reproduce

n/a

##### Related issues/PRs

None that I can see 

##### Suggest a fix

Not sure, it seems like something in upstream Gradle has changed in the 6.5 -> 6.6 upgrade, I was able to work around it by moving from configuration that ended up in GlobalSettings and re-implemented it in ignore files.

### PR DESCRIPTION
**Pull request by chschu**
This PR fixes #7601 by working around https://github.com/gradle/gradle/issues/17344. It does not change generator output.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java [hunk 1]
```diff
@@ -34,7 +34,9 @@
     private static ThreadLocal<Properties> properties = new InheritableThreadLocal<Properties>() {
         @Override
         protected Properties initialValue() {
-            return (Properties) System.getProperties().clone();
+            Properties copy = new Properties();
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java:37]: Thanks for the PR. Can you please add a 1-liner comment explaining why and mentioning https://github.com/gradle/gradle/issues/17344 ?

Comment (chschu) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/config/GlobalSettings.java:38]: Done. Thanks for reviewing!
