### PR TITLE
Properly decode $ref

### LINKED ISSUE #5720: [BUG] URI encoded $ref not properly decoded
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I wanted to generate a dart lib for flutter with the provided swagger yaml config. The problem is, that some of the generated class names contain spaces which are not valid. After writing a fix for it (PR #5693), I used swagger to edit the yaml. Swagger suggests to use `%20` instead of normal spaces inside `$ref` definition links because it's an URI (see [docs](https://swagger.io/docs/specification/using-ref/)). Now I got the problem, that some class names contain `%20`.

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/wbt-solutions/openproject_dart_sdk/master/openProject_swagger.yaml

##### Command line used for generation

I used the command `java -jar .\openapi-generator-cli-4.2.3.jar generate -g dart -i openProject_swagger.yaml  -o openproject_dart_sdk/` inside the Windows Powershell.

##### Steps to reproduce

Execute the command with the provided config and look for example in the *model\work_package.dart*.

##### Related issues/PRs

Haven't found any.

##### Suggest a fix

Properly decode the $ref attribute as URI.

### PR DESCRIPTION
**Pull request by sbu-WBT**
fixes #5720

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [ ] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java [hunk 1]
```diff
@@ -386,6 +388,11 @@ public static String getSimpleRef(String ref) {
 
         }
 
+        try {
+            ref = URLDecoder.decode(ref, "UTF-8");
+        } catch (UnsupportedEncodingException ignored) {
+        }
+
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java:395]: Shall we decode it at the start of the function `getSimpleRef` instead?

Comment (SimonIT) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java:395]: I had the same thought, but why decoding a String part which gets thrown away? I see no reason to do so

By the way, I think we should also unescape these special cases:
image

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java [hunk 2]
```diff
@@ -386,6 +388,13 @@ public static String getSimpleRef(String ref) {
...
+        ref = ref.replace("~1", "/").replace("~0", "~");
```
Comment (jimschubert) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java:396]:
```suggestion
        // see https://tools.ietf.org/html/rfc6901#section-3
        // Because the characters '~' (%x7E) and '/' (%x2F) have special meanings in
        // JSON Pointer, '~' needs to be encoded as '~0' and '/' needs to be encoded 
        // as '~1' when these characters appear in a reference token.
        // This reverses that encoding.
        ref = ref.replace("~1", "/").replace("~0", "~");
```

**Review by jimschubert — COMMENTED** [review]
Suggested comment on the escapes, so they don't get removed accidentally in the future.

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java (hunk 2 above)
Comment (sbu-WBT) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java:401]: @jimschubert Also added a unit test

**Comment by jimschubert** [comment]
I've added OAS 3.0 spec support because the JSON pointer escapes make sense for refs pointing to operations/paths.

I think this approach is good to merge even before we cut 5.0.0-beta2. Any thoughts @wing328?

**Review by wing328 — APPROVED** [review]
