### PR TITLE
Python flask pythonic params

### LINKED ISSUE #1671: [BUG][Python-Flask] camelCase path parameters are not converted to snake_case
##### Description

* We have _parameterized_ `paths` in our OpenAPI v3.x definition file.
* We generate a and start `python-flask` server.
* When trying to obtain the data, we get an internal server error and the server logs:
   ```
   [2018-12-14 10:20:05,725] ERROR in app: Exception on /data/123 [GET]
   Traceback (most recent call last):
     File "/home/tom/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
       response = self.full_dispatch_request()
   ...
     File "/home/tom/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
       response = function(request)
     File "/home/tom/.local/lib/python3.5/site-packages/connexion/decorators/parameter.py", line 131, in wrapper
       return function(**kwargs)
   TypeError: data_remote_id_get() got an unexpected keyword argument 'remoteId'
   127.0.0.1 - - [14/Dec/2018 10:20:05] "GET /data/123 HTTP/1.1" 500 -
   ```

The `camelCase` path parameter is not converted to a `snake_case` (== _pythonic_) function argument for the controller.

##### openapi-generator version

I used OpenAPI generator CLI version `4.0.0-SNAPSHOT`:
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.0.0-SNAPSHOT/openapi-generator-cli-4.0.0-20181210.103357-85.jar

##### OpenAPI declaration file content or url

See `python-flask-pythonic-params.yaml` in the attached zip-file:
[python-flask-pythonic-params.zip](https://github.com/OpenAPITools/openapi-generator/files/2679404/python-flask-pythonic-params.zip)

##### Command line used for generation

    java -jar openapi-generator-cli-4.x.jar generate -i ./python-flask-pythonic-params.yaml -g python-flask -o ./python-flask-pythonic-params/

##### Steps to reproduce

1. Generate the server code

       ./python-flask-pythonic-params.sh

2. Start the server

       (cd python-flask-pythonic-params && python3 -m openapi_server)

3. Perform a client request

       curl -X GET "http://localhost:8080/data/123" -H  "accept: application/json"

   Returns:
   ```
   {
     "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.",
     "status": 500,
     "title": "Internal Server Error",
     "type": "about:blank"
   }
   ```

##### Related issues/PRs

* #1856

##### Suggest a fix

Some suggestions (_feel free for other suggestions ;-)_):

1. Define `**kwargs` as argument in the controllers and get the (_non-pythonic_) argument via `kwargs['remoteId']`.
2. Provide `pythonic_params=True` to the connexion/Flask app.
   _I verified that this works_.

   In our example this would be:

   Replacing:
   ```
   app.add_api('openapi.yaml', arguments={'title': 'Test REST API'})
   ```
   by
   ```
   app.add_api('openapi.yaml', arguments={'title': 'Test REST API'}, pythonic_params=True)
   ```

   See also [zalando/connexion](https://github.com/zalando/connexion):

   * [#687](https://github.com/zalando/connexion/issues/687) - pythonic_params does not cover the path params

### PR DESCRIPTION
**Pull request by tomghyselinck**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh`, `./bin/security/{LANG}-petstore.sh` and `./bin/openapi3/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language. -- @wing328 @taxpon @frol @mbohlool @cbornet @kenjones-cisco @tomplus @Jyhess

### Description of the PR

We have an OpenAPI spec file with `camelCase` (_query_ and _path_) parameters.
When generating a Python (`connexion`-based) server those parameters are converted to ("_pythonic_") `snake_case` parameters.

During generation of the supporting files there is also an OpenAPI spec file generated for use with `connexion`. This spec file does not match the original one regarding parameter names.

Especially when defining "_query_" parameters, the REST interface will be different than the one defined in the original OpenAPI spec file.
Such (_query_) parameters are incompatible with generated clients (and other server implementations)

Fixes #1671

We have been using this fix some time on a local checkout for generating `python-flask` server implementations without issues.

### Notes ###

1. This PR also updates the `python-aiohttp` but it is untested.
    Please feel free to try it out.

2. These changes do not limit on _query_ or _path_ parameters and should also work on _header_ and _cookie_ parameters.

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java [hunk 1]
```diff
@@ -474,6 +476,70 @@ else if ("bearer".equals(securityScheme.getScheme())) {
...
+
+            // Sort path names after variable name fix
+            List<String> recoveredPathnames = new ArrayList(paths.keySet());
+            Collections.sort(recoveredPathnames);
+            for (String pathname: recoveredPathnames) {
+                PathItem pathItem = paths.remove(pathname);
+                paths.put(pathname, pathItem);
+            }
+        }
+        //objs.put("openAPI", openAPI);
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java]: @tomghyselinck thanks for the PR, which looks good to me.

One minor suggestion: shall we remove line 541 and 486, which are commented out already?

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonAbstractConnexionServerCodegen.java]: I'll do that in a separate PR when I've time. Thanks again for the PR.

File: modules/openapi-generator/src/test/resources/3_0/petstore.yaml [hunk 2]
```diff
@@ -116,6 +116,13 @@ paths:
             type: array
             items:
               type: string
+        - name: maxCount
+          in: query
+          description: Maximum number of items to return
+          required: false
+          schema:
+            type: integer
+            format: int32
```
Comment (wing328) [inline modules/openapi-generator/src/test/resources/3_0/petstore.yaml]: We'll remove this as we want to keep 

Additional test cases should go to https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml instead
