### PR TITLE
[Swift5] Fix Datetime default value

### LINKED ISSUE #5256: [BUG][JAVA][MAVEN] java.time.OffsetDateTime cannot be cast to java.lang.String
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generation of client classes fails with class cast Exception while generation using maven Plugin.
Running `mvn clean compile` fails with 
```
[ERROR] 
java.lang.RuntimeException: Could not process operation:
  Tag: class Tag {
    name: Process
    description: REST-Services.
    externalDocs: null
}
  Operation: getProcessUsingGET
  Resource: get /api/prozesse
  Schemas: {}
  Exception: java.time.OffsetDateTime cannot be cast to java.lang.String
```

##### openapi-generator version

4.2.3
(Happens also in earlier Versions of 4.x.x)

##### OpenAPI declaration file content or url
The Spec used: (its valid according to https://apitools.dev/swagger-parser/online/ and https://editor.swagger.io/ )

```yaml
swagger: '2.0'
info:
  description: 'REST service'
  version: '2.1.9'
  title: REST
host: localhost
basePath: /
tags:
  - name: Process
    description: REST-Services.
paths:
  /api/prozesse:
    get:
      tags:
        - Process
      summary: Return a list of Process
      description: |
        Max response time MAX_RESPONSE_TIME_MS=20
      operationId: getProcessUsingGET
      produces:
        - application/json;charset=utf-8
      parameters:
        - name: dateFrom
          in: query
          description: Filters out Transactions before this date
          required: true
          type: string
          default: '2000-01-01T00:00:00.001Z'
          format: date-time
          allowEmptyValue: false
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - bearer: []
      deprecated: false
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
```

Used pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<artifactId>failing-with-class-cast-exception</artifactId>
	<name>failing-with-class-cast-exception</name>
	<groupId>com.example</groupId>
	<version>0.0.1-SNAPSHOT</version>
	<build>
		<plugins>
			<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>4.2.3</version>
				<executions>
					<execution>
						<id>kto-privatkunde</id>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>process.yml</inputSpec>
							<generatorName>java</generatorName>
							<generateApiTests>false</generateApiTests>
							<generateModelTests>false</generateModelTests>
							<configOptions>
								<library>jersey2</library>
								<hideGenerationTimestamp>true</hideGenerationTimestamp>
								<delegatePattern>true</delegatePattern>
								<java8>java8</java8>
								<dateLibrary>java8</dateLibrary>
							</configOptions>
							<additionalProperties>failOnEmptyBeans=false</additionalProperties>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```
##### Command line used for generation

`mvn clean compile`

##### Steps to reproduce

Setup maven project and run `mvn clean compile`

### PR DESCRIPTION
**Pull request by Allezxandre**
This is a follow-up to #5256, which happens to affect the Swift5 code-gen.

If a default value is provided by the API spec for a date-time attribute, this PR fixes the generation code to build a correct Swift `Date` object.

To close #5256

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language: @4brunu

### CODE REVIEW

**Comment by 4brunu** [comment]
Can you please run `./mvnw package && ./bin/generate-samples.sh bin/configs/other/swift5-*` and commit the changes?

**Comment by wing328** [comment]
I've updated the samples via 80f9612c. Let's see how that goes.

**Comment by 4brunu** [comment]
It looks like the samples don't have a default date value, so this PR will be difficult to validate.
@Allezxandre could you please test this changes locally?

File: samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift [hunk 1]
```diff
@@ -12,7 +12,7 @@ public struct AdditionalPropertiesClass: Codable {
     public var mapString: [String: String]?
     public var mapMapString: [String: [String: String]]?
 
-    public init(mapString: [String: String]?, mapMapString: [String: [String: String]]?) {
+    public init(mapString: [String: String]? = nil, mapMapString: [String: [String: String]]? = nil) {
```
Comment (wing328) [inline samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift:15]: @Allezxandre looks like many parameters are default to `nil`. Is that expected?

Comment (4brunu) [reply samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift:15]: This is not related to this PR, it was introduced in another one, but apparently the samples were outdated.

**Comment by Allezxandre** [comment]
> It looks like the samples don't have a default date value, so this PR will be difficult to validate.
> @Allezxandre could you please test this changes locally?

I tested this locally, and this yields the following default date when it is defined to March 17th 2020 10:00:00 UTC:

```
Date(timeIntervalSince1970: 1584439200000000.0 / 1_000_000)
```

File: samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift (hunk 1 above)
Comment (wing328) [reply samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift:15]: I actually tested with the master but didn't get these `nil` default value. Maybe my test wasn't done right.

Comment (4brunu) [reply samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift:15]: Let me test on master

Comment (4brunu) [reply samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift:15]: When I run `./mvnw package && ./bin/generate-samples.sh bin/configs/other/swift5-*` on the master, I get all of those `nil` changes

**Comment by 4brunu** [comment]
Is there any disadvantages in removing the division like this?
`Date(timeIntervalSince1970: 1584439200)`

File: samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift (hunk 1 above)
Comment (wing328) [reply samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift:15]: Thanks for confirming that. 

Is the `nil` default value expected? If not, we can remove it later in another PR. ( I think I know where to fix it )

Comment (4brunu) [reply samples/client/petstore/swift5/alamofireLibrary/PetstoreClient/Classes/OpenAPIs/Models/AdditionalPropertiesClass.swift:15]: Yes it is expected. 
Basically this is just providing default `nil` values for for nullable types to shorten the constructor to the library user.

**Comment by Allezxandre** [comment]
> Is there any disadvantages in removing the division like this?
> `Date(timeIntervalSince1970: 1584439200)`

This is because the date time can be expressed up to the microsecond precision. However, in Java they are represented as Microseconds stored in a long and in Swift they are represented as seconds represented in a double.

To avoid float precision issue, I let Java keep its storage as a long, and then add a `.0` and let the Swift compiler divide by a million to get the seconds stored in a double. 

In my example of a `1584439200.0` seconds timestamp, the date I used has 0 minutes, 0 seconds, 0 milliseconds, and 0 microseconds, so I guess it would be smarter in that case to remove the division. However, in other cases with dates that are not rounded like that, the division would prove useful.

**Comment by 4brunu** [comment]
Thanks for the explanation, looks good to me 👍
