### PR TITLE
[bug][html2] Fix visibility of body/response schemas

### LINKED ISSUE #1441: [html2] missing body/response schema documentation
##### Description

I'm generating html2 documentation from modules/openapi-generator/src/test/resources/2_0/rust-server/rust-server-test.yaml.

I've noticed that the html2 docs seem to be missing the body and response schemas. These were present when generated in swagger-codegen

New (openapi-generator): https://bgill.eu/openapi-generator/issues/new-html2.html#api-Default-htmlPost
Old (swagger-codegen): https://bgill.eu/openapi-generator/issues/old-html2.html#api-Default-htmlPost

##### OpenAPI declaration file content or url

[modules/openapi-generator/src/test/resources/2_0/rust-server/rust-server-test.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/rust-server/rust-server-test.yaml)

### PR DESCRIPTION
**Pull request by degath**
These changes fill schemas in html2 (not only single objects, but also collections).
Tested manually. 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [ ] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.
It's simple JavaScript method inside mustache templates so I copied JavaScript Committee
 @CodeNinjai (2017/07) @frol (2017/07) @cliffano (2017/07)

To fix #1441

### CODE REVIEW

**Comment by masci** [comment]
This PR would fix #1441

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java [hunk 1]
```diff
@@ -5482,13 +5482,20 @@ public CodegenParameter fromRequestBody(RequestBody body, Set<String> imports, S
...
         // set the parameter's example value
         // should be overridden by lang codegen
         setParameterExampleValue(codegenParameter, body);
 
         return codegenParameter;
     }
 
+    private void addJsonSchemaForBodyRequestInCaseItsNotPresent(CodegenParameter codegenParameter, RequestBody body){
+        if(codegenParameter.jsonSchema == null)
+            codegenParameter.jsonSchema = Json.pretty(body);
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java:5496]: I wonder if you can share a minimal spec to reproduce the issue fixed by this change?

File: modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache [hunk 2]
```diff
@@ -416,7 +441,10 @@
...
                                       $(document).ready(function() {
                                         var schemaWrapper = {{{jsonSchema}}};
-                                        var schema = schemaWrapper.schema;
+                                        var schema = findNode('schema',schemaWrapper).schema;
+                                        if (!schema) {
+                                            schema = schemaWrapper.schema;
+                                        }
                                         if (schema.$ref != null) {
                                           schema = defsParser.$refs.get(schema.$ref);
                                         } else {
```
Comment (astoialtsev) [inline modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache:450]: This does not cover array type, e.g.:
```yaml
schema:
  type: array
  items:
    ref: '#/components/schemas/Pet'
```

So I had to add one more `if` statement:
```javascript
...
} else if (schema.type === 'array' && schema.items != null && schema.items.$ref != null) {
    schema.items = defsParser.$refs.get(schema.items.$ref);
} else {
    // line 450
}
```

**Comment by jimschubert** [comment]
@wing328 this affects every spec. You can see the current samples, none of which display body parameter information.

**Comment by jimschubert** [comment]
Assigned myself. I'd begun looking at this a month or two ago, but never got very far. The solution here seems very reasonable. I'll just test a bit before merge.

**Comment by jimschubert** [comment]
I've tested with proposal from @astoialtsev:

```diff
diff --git a/modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache b/modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache
index 4d39e6c014..e82cd10725 100644
--- a/modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache
+++ b/modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache
@@ -447,6 +447,8 @@
                                         }
                                         if (schema.$ref != null) {
                                           schema = defsParser.$refs.get(schema.$ref);
+                                        } else if (schema.items != null && schema.items.$ref != null) {
+                                            schema.items = defsParser.$refs.get(schema.items.$ref);
                                         } else {
                                           schemaWrapper.definitions = Object.assign({}, defs);
                                           $RefParser.dereference(schemaWrapper).catch(function(err) {

```

And this seems to work as expected:

image

@degath could you resolve the attribution issue mentioned above (`git commit --amend --author="Your Name <your@email.com>"`)? If you want to message us at team@openapitools.org, we can also fix this for you and apply the diff above.

File: modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache (hunk 2 above)
Comment (degath) [reply modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache:450]: You're totally right. I tested it on two different versions of the OpenApi generator and on the older one there was no issue with arrays, so I didn't cover it up, but that's a great change.

**Comment by degath** [comment]
@jimschubert  attribution issue resolved (commit amended)

**Comment by jimschubert** [comment]
Thanks @degath I'll fix up a couple other things and merge. Everything looks good. Thanks for the contribution!

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java (hunk 1 above)
Comment (jimschubert) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java:5496]: I commented on my phone, and this was attached at the PR level rather than response here. I'm duplicating my response here in case you didn't see it.

This affects every spec. You can see the current samples, none of which display body parameter information.

File: modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache (hunk 2 above)
Comment (jimschubert) [reply modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache:452]: I've applied the suggested fix to this branch.

**Comment by jimschubert** [comment]
CircleCI failure is not related to changes in this PR.

**Comment by wing328** [comment]
@degath thanks for the PR, which has been included in the v4.3.1 release: https://twitter.com/oas_generator/status/1258057660974329861
