### PR TITLE
[Java] Add a new additional property to configure Jackson's `failOnUnknownProperties`

### LINKED ISSUE #10306: Disable FAIL_ON_UNKNOWN_PROPERTIES in generated JSON.java?
##### Description

I get com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException because the API I am using has a new field.
But I want my client to be able to just ignore unknown properties.
In a previous project I used openapi generator 4.3.1 and this was the behaviour.
However in newer versions like 5.1.1 or 5.2.1 this doesn't work anymore. I can see that in the generated invoker.JSON.java the FAIL_ON_UNKNOWN_PROPERTIES changed from false to true.
How can I configure the openapi generator, to ignore unknown properties, like it was before?

##### openapi-generator version

Worked in 4.3.1. Not anymore in 5.x

### PR DESCRIPTION
**Pull request by fistons**
@martin-mfg

This MR should fix #10306

It adds a new additional and non mandatory property to change the generated Jackson's ObjectMapper's FAIL_ON_UNKNOWN_PROPERTIES's value

If this property is not set, we keep the default value, i.e. `true`

### PR checklist
 
- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [X] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.6.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [X] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java [hunk 1]
```diff
@@ -322,6 +325,7 @@ public AbstractJavaCodegen() {
         cliOptions.add(CliOption.newString(ADDITIONAL_MODEL_TYPE_ANNOTATIONS, "Additional annotations for model type(class level annotations). List separated by semicolon(;) or new line (Linux or Windows)"));
         cliOptions.add(CliOption.newString(ADDITIONAL_ONE_OF_TYPE_ANNOTATIONS, "Additional annotations for oneOf interfaces(class level annotations). List separated by semicolon(;) or new line (Linux or Windows)"));
         cliOptions.add(CliOption.newBoolean(OPENAPI_NULLABLE, "Enable OpenAPI Jackson Nullable library", this.openApiNullable));
+        cliOptions.add(CliOption.newBoolean(FAIL_ON_UNKNOWN_PROPERTIES, "Fail Jackson de-serialization on unknown properties", this.failOnUnknownProperties));
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java:328]: shall we add this option to java client codegen java class only as only java client needs this option?

Comment (fistons) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java:328]: Indeed, that's a good idea, I will make the change

File: modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON_jackson.mustache [hunk 2]
```diff
@@ -30,7 +30,7 @@ public class JSON implements ContextResolver<ObjectMapper> {
     mapper = JsonMapper.builder()
             .serializationInclusion(JsonInclude.Include.NON_NULL)
             .configure(MapperFeature.ALLOW_COERCION_OF_SCALARS, false)
-            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true)
+            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, {{failOnUnknownProperties}})
```
[the remark this answers is not in the document]
Comment (fistons) [reply modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON_jackson.mustache:33]: Hi, yes, I can do this, the only issue is that some libraries are configured to fail on unknown properties, some aren't.

I see that `apache-httpclient`, `feign`, `google-api-client`, `restassured`, `restclient`, `resteasy`, `vertx` and `webclient` currently have `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` set to `false`, whereas `jersey2`, `jersey3`, `native` and `retrofit2` have `DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES` set to `true` 

Is there an elegant way to tell JavaClientCodegen to default the `failOnUnknownProperties` variable to true or false, depending of the chosen library?

[the remark this answers is not in the document]
Comment (martin-mfg) [reply modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON_jackson.mustache:33]: Good point.

My preferred approach would be to use this opportunity to unify the behaviour of the different libraries. Since the majority uses `false` as default, let's make `false` the default value of `failOnUnknownProperties` for all libraries.
This would also make this PR a "breaking change with fallback", i.e. it should become part of OpenAPI Generator 7.8.0, not of 7.7.1. But I think wing328 will take care of this aspect.

[the remark this answers is not in the document]
Comment (fistons) [reply modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON_jackson.mustache:33]: It's done!

[the remark this answers is not in the document]
Comment (martin-mfg) [reply modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON_jackson.mustache:33]: Thank you!

Some tests in `samples/openapi3/client/petstore/java/jersey2-java8/` are failing now. Apparently due to the custom deserialization logic in this sample, which relies on `FAIL_ON_UNKNOWN_PROPERTIES` being `true`. Can you please fix this by simply adding in `bin/configs/java-jersey2-8.yaml` the following line somewhere under `additionalProperties:`?
```java
  failOnUnknownProperties: true
```

[the remark this answers is not in the document]
Comment (fistons) [reply modules/openapi-generator/src/main/resources/Java/libraries/retrofit2/JSON_jackson.mustache:33]: Fixed! Thanks for the hint, I had trouble finding where it came from

**Review by martin-mfg — APPROVED** [review]

File: modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache [hunk 3]
```diff
@@ -30,7 +30,7 @@ public class JSON implements ContextResolver<ObjectMapper> {
     mapper = JsonMapper.builder()
             .serializationInclusion(JsonInclude.Include.NON_NULL)
             .configure(MapperFeature.ALLOW_COERCION_OF_SCALARS, false)
-            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true)
+            .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, {{failOnUnknownProperties}})
```
Comment (ashirman) [inline modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache:33]: are there plans to have something similar for Kotlin generators too? I got exactly the same issue using Kotlin + okhttp3 client and seems like [there](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache#L113) we use the same properties and in Java's generators.

Comment (fistons) [reply modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache:33]: I can probably take a look once this PR is merged. Is there a issue already?

Comment (ashirman) [reply modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache:33]: thanks a lot. I am not aware of formal issue yet but please let me know if I should open one.

Comment (fistons) [reply modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache:33]: Yes, that would be great!

Comment (ashirman) [reply modules/openapi-generator/src/main/resources/Java/libraries/jersey3/JSON.mustache:33]: here it is https://github.com/OpenAPITools/openapi-generator/issues/19408 . Thanks!

**Comment by fistons** [comment]
> Can we entertain the possibility of defaulting `FAIL_ON_UNKNOWN_PROPERTIES` to false? There is no sane client/server configuration where this should be true.

That would be the new default with this MR

**Comment by wing328** [comment]
thanks for the PR, which has been merged
