### PR TITLE
Sttp - wrap query params

### LINKED ISSUE #6883: [BUG] scala-sttp string interpolation with backticks compiler error
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ 5.0.0-beta] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

If REST API method parameter is called `type` with backticks, then Scala compiler fails with:

```
nifi-client/target/generated-sources/openapi/src/gen/scala/main/org/openapitools/client/api/FlowApi.scala:569: error: invalid string interpolation $`, expected: $$, $identifier or ${expression}
[ERROR]       .method(Method.GET, uri"$baseUrl/flow/processor-types?bundleGroupFilter=$bundleGroupFilter&bundleArtifactFilter=$bundleArtifactFilter&type=$`type`")
```
Example is taken from NiFi REST API: https://nifi.apache.org/docs/nifi-docs/rest-api/index.html

Expected behavior: code compiles without an y error.

##### Command line used for generation

mvn clean install

##### Steps to reproduce

1. Use Maven plugin:
```
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>5.0.0-beta</version>
```
2. Specify generator as:
```
<generatorName>scala-sttp</generatorName>
```
3. Specify NiFi swagger JSON file
4. Run `mvn clean install`

##### Suggest a fix

Possible solution: wrap Scala keyword like name, i.e. `type` with curly braces. i.e. generated string must be like this:

```scala
.method(Method.GET, uri"$baseUrl/flow/processor-types?bundleGroupFilter=$bundleGroupFilter&bundleArtifactFilter=$bundleArtifactFilter&type=${`type`}")
```

CC @ghostbuster91

### PR DESCRIPTION
**Pull request by ghostbuster91**
This fixes #6883 

Provided solution generates additional spaces around `paramName`.

Alternative solution to fix this would be to create a custom lambda to wrap arbitrary expression in curly braces in sttp generator and register it within `additionalProperties`.

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [X] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [X] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [X] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@clasnake (2017/07), @jimschubert (2017/09) , @shijinkui (2018/01), @ramzimaalej (2018/03), @chameleon82 (2020/03), @Bouillie (2020/04)

### CODE REVIEW

File: samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala [hunk 1]
```diff
@@ -67,7 +67,7 @@ class PetApi(baseUrl: String) {
   def findPetsByStatus(status: Seq[String]
 ): Request[Either[ResponseError[Exception], Seq[Pet]], Nothing] =
     basicRequest
-      .method(Method.GET, uri"$baseUrl/pet/findByStatus?status=$status")
+      .method(Method.GET, uri"$baseUrl/pet/findByStatus?status=${ status }")
```
Comment (novakov-alexey) [inline samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala:70]: Looks promising! Does it make sense to wrap only those which have backticks or it is not easy?

Comment (ghostbuster91) [reply samples/client/petstore/scala-sttp/src/main/scala/org/openapitools/client/api/PetApi.scala:70]: It it for sure an additional complication which doesn't bring any value IMO.

**Comment by novakov-alexey** [comment]
@ghostbuster91 do you have any idea when this fix could be released?

**Comment by ghostbuster91** [comment]
@novakov-alexey I am not a maintainer of this project, you have to ask somebody from the committee.

**Comment by wing328** [comment]
If no further feedback on this, I'll merge it over the weekend.

**Comment by ghostbuster91** [comment]
Thanks!
