### PR TITLE
[kotlin] Fix imports of generated class

### LINKED ISSUE #7313: [BUG] kotlin-spring generator resolves invalid package for imports form importMap
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

`kotlin-spring` generator resolves invalid package name when using `importMappings`.

```xml
<configuration>
  <apiPackage>com.example.api</apiPackage>
  <importMappings>Problem=org.zalando.problem.Problem</importMappings>
</configuration>                    
```
resolves to: import com.example.model.org.zalando.problem.Problem;` instead of `import org.zalando.problem.Problem;`

The generation of the Java Spring version with the same `api.yml` works correctly.

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

```yaml

# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.3'

info:
  title: demo
  version: 1.0.0

servers:
  - url: http://localhost:8080/api
    description: Local server

tags:
  - name: Account

paths:
  /accounts:
    get:
      tags:
        - Account
      operationId: listAccounts
      responses:
        '200':
          description: List of all available accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '404':
          $ref: '#/components/responses/Problem'
  /error:
    get:
      tags:
        - Account
      operationId: error
      responses:
        '200':
          $ref: '#/components/responses/Problem'

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          description: Konto Laufnummer
          type: integer
          format: int64
        accountOwnerId:
          description: Kundennummer
          type: string
          maxLength: 12
        accountNumber:
          description: Kontonummer
          type: string
          maxLength: 20

  responses:
    Problem:
      description: error occurred - see status code and problem object for more information.
      content:
        'application/problem+json':
          schema:
            $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          example:
            url: https://zalando.com/problem/not-found
            title: Resource not found
            status: 404
            detail: index.html not found
            instance: /account/not-found
```

##### Generation Details

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.3.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>11</java.version>
        <kotlin.version>1.3.72</kotlin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-reflect</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>org.zalando</groupId>
            <artifactId>problem-spring-web-starter</artifactId>
            <version>0.25.2</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-kotlin</artifactId>
            <version>1.4.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <configuration>
                    <args>
                        <arg>-Xjsr305=strict</arg>
                    </args>
                    <compilerPlugins>
                        <plugin>spring</plugin>
                    </compilerPlugins>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

            <plugin>
                <!--
                    Plugin that provides API-first development using openapi-generator to
                    generate Spring-MVC endpoint stubs at compile time from an OpenAPI definition file
                -->
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.2.3</version>
                <executions>
                    <execution>
                        <id>generate-kotlin-spring</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <apiPackage>com.example.api</apiPackage>
                            <generateApiTests>false</generateApiTests>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <generatorName>kotlin-spring</generatorName>
                            <importMappings>Problem=org.zalando.problem.Problem</importMappings>
                            <inputSpec>${project.basedir}/src/main/resources/api.yml</inputSpec>
                            <modelPackage>com.example.model</modelPackage>
                            <skipValidateSpec>false</skipValidateSpec>
                            <configOptions>
                                <basePackage>com.example</basePackage>
                                <exceptionHandler>false</exceptionHandler>
                                <enumPropertyNaming>UPPERCASE</enumPropertyNaming>
                                <interfaceOnly>false</interfaceOnly>
                                <serviceInterface>true</serviceInterface>
                                <sourceFolder>src/main/kotlin</sourceFolder>
                                <title>${project.artifactId}</title>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

##### Steps to reproduce

- save `pom.xml`
- save `api.yml` and save to `src/main/resources/api.yml`
- run `mvn install`

##### Suggest a fix

Apply same logic as for the `AbstractJavaCodeGen`

```Java
   @Override
    protected boolean needToImport(String type) {
        return super.needToImport(type) && !type.contains(".");
    }
```

Alternative fix is to provide 2 import mappings. One to map the entity to the actual class name and another to prevent that the API package is used as prefix.

```xml                                
  
<importMappings>Problem=org.zalando.problem.Problem,org.zalando.problem.Problem=org.zalando.problem.Problem</importMappings>
```

### PR DESCRIPTION
**Pull request by michael-wirth**
To fix #7313

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by wing328** [comment]
cc @jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11) @yutaka0m (2020/03)

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java [hunk 1]
```diff
@@ -771,7 +771,9 @@ protected boolean isReservedWord(String word) {
     @Override
     protected boolean needToImport(String type) {
         // provides extra protection against improperly trying to import language primitives and java types
-        boolean imports = !type.startsWith("kotlin.") && !type.startsWith("java.") && !defaultIncludes.contains(type) && !languageSpecificPrimitives.contains(type);
+        boolean imports = !type.startsWith("kotlin.") && !type.startsWith("java.") &&
+                !defaultIncludes.contains(type) && !languageSpecificPrimitives.contains(type) &&
+                !type.contains(".");
```
Comment (jimschubert) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java:776]: Interesting. I was trying to think of a case where this would fall through, but can't really. Seems like any type with a dot in the name can be assumed to be fully qualified.

If people report it as a bug, we can always adjust. In that unlikely event, it may result in a regression since the change isn't covered by a unit test.

**Review by jimschubert — APPROVED** [review]
