### PR TITLE
[Java][jersey2] Fix `serializeToString`

### LINKED ISSUE #6954: [BUG][Java][jersey2] Incorrect serialization of HTTP GET request body
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When a HTTP message digest needs to be calculated for inclusion in a HTTP signature, the [serializeToString()](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache#L914) helper function is invoked to serialize the HTTP body, then that serialized value is used to calculate a cryptographic hash of the body, which is set in the `Digest` header. There are several use cases:

1. The body is not set (`obj` argument is `null`). For example, HTTP GET requests must have an empty body.
1. The body is set to the empty string. For example a HTTP POST request where the body is the empty string.
1. The body is the JSON value `null`. For example, a HTTP POST request body may contain the JSON `null` value.
1. The body is the JSON string `"null"`. For example, a HTTP POST request body may contain the JSON `"null"` value.
1. The body is some other non-null value.

For use case (1), the serializeToString() function incorrectly returns the String `null`. Instead the function should return the empty string "". Note: in the case of HTTP GET, the `isBodyNullable` argument is `false` and the `obj` argument is `null`.

##### openapi-generator version

master July 15 2020

##### Suggest a fix

I had opened a PR earlier: https://github.com/OpenAPITools/openapi-generator/pull/6634, it was properly handling the HTTP GET case, but the code has diverged since then.

### PR DESCRIPTION
**Pull request by wing328**
To fix #6954 

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/config/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

cc @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10) @bkabrda (2020/01)

### CODE REVIEW

**Comment by sebastien-rosset** [comment]
Fix for #6956

File: samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+        assertEquals("null", apiClient.serializeToString(null, null, "application/json", true));
+
+        // non-nullable empty string should give "\"\"" (empty json string)
+        assertEquals("\"\"", apiClient.serializeToString("", null, "application/json", false));
+        // nullable null empty string should give "\"\"" (empty json string)
+        assertEquals("\"\"", apiClient.serializeToString("", null, "application/json", true));
+
+        // non-nullable string "null"  should give "\"null\""
+        assertEquals("\"null\"", apiClient.serializeToString("null", null, "application/json", false));
+        // nullable string "string" should give "\"null\""
```
Comment (sebastien-rosset) [inline samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java:60]: Did you mean
```suggestion
        // nullable string "null" should give "\"null\""
```

File: samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+        assertEquals(result, apiClient.serializeToString(pet, null, "application/json", true));
+
+        // non-nullable null object should give "" (empty body)
+        assertEquals("", apiClient.serializeToString(null, null, "application/json", false));
+        // nullable null object should give "null"
+        assertEquals("null", apiClient.serializeToString(null, null, "application/json", true));
+
+        // non-nullable empty string should give "\"\"" (empty json string)
+        assertEquals("\"\"", apiClient.serializeToString("", null, "application/json", false));
+        // nullable null empty string should give "\"\"" (empty json string)
```
Comment (sebastien-rosset) [inline samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java:55]: Did you mean?
```suggestion
        // nullable empty string should give "\"\"" (empty json string)
```

File: samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+        tag.setId(petId);
+        tag.setName("jersey2 java8 tag");
+        pet.setTags(Arrays.asList(tag));
+
+        String result = "{\"id\":4321,\"category\":{\"id\":4321,\"name\":\"jersey2 java8 category\"},\"name\":\"jersey2 java8 pet\",\"photoUrls\":[\"A\",\"B\",\"C\"],\"tags\":[{\"id\":4321,\"name\":\"jersey2 java8 tag\"}],\"status\":\"available\"}";
+        assertEquals(result, apiClient.serializeToString(pet, null, "application/json", false));
+        // nulllable and there should be no diffencne as the payload is not null
+        assertEquals(result, apiClient.serializeToString(pet, null, "application/json", true));
+
+        // non-nullable null object should give "" (empty body)
```
Comment (sebastien-rosset) [inline samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java:48]: I think this use case is non trivial to understand because there may be two variants:
1. The request is supposed to have an empty body by design, i.e. the OpenAPI doc request or response schema indicates the body is empty.
1. The client or server is setting the data incorrectly. I.e. the OpenAPI doc indicates the object is not nullable, but the actually either the client or server are setting to a null value.

Is it even possible?

Comment (wing328) [reply samples/openapi3/client/petstore/java/jersey2-java8/src/test/java/org/openapitools/client/ApiClientTest.java:48]: > The client or server is setting the data incorrectly

This can be prevented by marking the "body" parameter (OAS v2 term) as required.
