### PR TITLE
Kotlin-Client: Fix kotlinx_serialization

### LINKED ISSUE #9242: [BUG][KOTLIN CLIENT] Generator generates invalid code when using kotlinx.serialization
##### Description

Generator generates invalid code when using kotlinx.serialization

##### openapi-generator version

5.1.0 installed from the official ArchLinux package repository

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Generation Details

openapi-generator generate -g kotlin -i petstore.yaml -p serializationLibrary=kotlinx_serialization

##### Steps to reproduce

 - Run above command to generate the source code
 - Run `gradle build`
 - Observe the following error message
```
e: /tmp/oas/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (118, 29): Expecting an element
e: /tmp/oas/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (101, 82): Type mismatch: inferred type is T but DeserializationStrategy<TypeVariable(T)> was expected
e: /tmp/oas/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (101, 89): No value passed for parameter 'string'
e: /tmp/oas/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (101, 91): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public final fun ByteArray.toRequestBody(contentType: MediaType? = ..., offset: Int = ..., byteCount: Int = ...): RequestBody defined in okhttp3.RequestBody.Companion
public final fun String.toRequestBody(contentType: MediaType? = ...): RequestBody defined in okhttp3.RequestBody.Companion
public final fun ByteString.toRequestBody(contentType: MediaType? = ...): RequestBody defined in okhttp3.RequestBody.Companion
e: /tmp/oas/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (249, 50): Type mismatch: inferred type is T but SerializationStrategy<TypeVariable(T)> was expected
e: /tmp/oas/src/main/kotlin/org/openapitools/client/infrastructure/ApiClient.kt: (249, 55): No value passed for parameter 'value'
```

##### Suggest a fix

This line is probably missing support for kotlinx.serialization: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache#L175

### PR DESCRIPTION
**Pull request by saschpe**
And update to Kotlin 1.5.0 and kotlinx.serialization 1.2.1. Fix nested
enum annotation '@Serializable' instead of '@KSerializable' when
'kotlinx_serialization' is used. Fix missing JsonMediaType in
ApiClient.kt (#9242). Add 'kotlinx_serialization' serialization library
to documentation.

Resolves #9242

@jimschubert @rsinukov @wing328 @dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m

Tested with `serializationLibrary` set to `gson`, `kotlinx_serialization` and default (`moshi`) as well as `library` set to `multiplatform` and default (`jvm-okhttp4`).

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `5.1.x`, `6.0.x`
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

File: modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/RequestConfig.kt.mustache [hunk 1]
```diff
@@ -8,10 +8,10 @@ package {{packageName}}.infrastructure
...
  *       multi-valued headers as csv-only.
  */
-{{#nonPublicApi}}internal {{/nonPublicApi}}data class RequestConfig(
+{{#nonPublicApi}}internal {{/nonPublicApi}}data class RequestConfig<T>(
     val method: RequestMethod,
     val path: String,
     val headers: MutableMap<String, String> = mutableMapOf(),
     val query: MutableMap<String, List<String>> = mutableMapOf(),
-    val body: kotlin.Any? = null
+    val body: T? = null
```
Comment (4brunu) [inline modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/RequestConfig.kt.mustache:16]: I wonder if this change has other hidden implications...

File: modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache [hunk 2]
```diff
@@ -71,8 +71,8 @@ import {{packageName}}.infrastructure.toMultiValue
     {{#isDeprecated}}
     @Deprecated(message = "This operation is deprecated.")
     {{/isDeprecated}}
-    fun {{operationId}}RequestConfig({{#allParams}}{{{paramName}}}: {{{dataType}}}{{^required}}?{{/required}}{{^-last}}, {{/-last}}{{/allParams}}) : RequestConfig {
-        val localVariableBody: kotlin.Any? = {{#hasBodyParam}}{{#bodyParams}}{{{paramName}}}{{/bodyParams}}{{/hasBodyParam}}{{^hasBodyParam}}{{^hasFormParams}}null{{/hasFormParams}}{{#hasFormParams}}mapOf({{#formParams}}"{{{baseName}}}" to {{{paramName}}}{{^-last}}, {{/-last}}{{/formParams}}){{/hasFormParams}}{{/hasBodyParam}}
+    private fun {{operationId}}RequestConfig({{#allParams}}{{{paramName}}}: {{{dataType}}}{{^required}}?{{/required}}{{^-last}}, {{/-last}}{{/allParams}}) : RequestConfig<{{#hasBodyParam}}{{#bodyParams}}{{{dataType}}}{{/bodyParams}}{{/hasBodyParam}}{{^hasBodyParam}}{{^hasFormParams}}Unit{{/hasFormParams}}{{#hasFormParams}}Map<String, Any>{{/hasFormParams}}{{/hasBodyParam}}> {
```
[the remark this answers is not in the document]
Comment (saschpe) [reply modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache:74]: Ok, that's easy to revert.

File: modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/RequestConfig.kt.mustache (hunk 1 above)
Comment (saschpe) [reply modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/RequestConfig.kt.mustache:16]: Others than providing stronger (or previously missing) type information, I don't think so. I generated code for several combinations of `library` and `serializationLibrary` but didn't run all of them. However, previously not a single combination worked reliably.

**Comment by 4brunu** [comment]
Could you please remove the changes from https://github.com/OpenAPITools/openapi-generator/pull/9358?
Because that makes it harder to review and merge it.

File: modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/RequestConfig.kt.mustache (hunk 1 above)
Comment (4brunu) [reply modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/RequestConfig.kt.mustache:16]: Just to be clearer, I like this change, I think it makes sense, I was just thinking if this could have some side effects that I didn't think of.

File: modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache [hunk 3]
```diff
@@ -1,48 +1,27 @@
...
-{{/jvm-okhttp3}}
-{{#jvm-okhttp4}}
-import okhttp3.RequestBody.Companion.asRequestBody
-import okhttp3.RequestBody.Companion.toRequestBody
-{{/jvm-okhttp4}}
-import okhttp3.FormBody
-{{#jvm-okhttp3}}
-import okhttp3.HttpUrl
-{{/jvm-okhttp3}}
+import okhttp3.*
```
Comment (4brunu) [inline modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache:3]: I'm not the biggest fan o star imports, but maybe this is only a matter of tast

Comment (4brunu) [reply modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache:3]: @saschpe although this may be a controversial subject, after reading a bit more on the subject, I think I would prefer keep the previous structure.
The main reason for this is because when reviewing PR's here on github, and we don't have the IDE to help figure out where the types comes from, so I would prefer to continue doing the imports explicitly.
So could you please revert the imports, to avoid using star import's?
Thanks

Comment (saschpe) [reply modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache:3]: I don't mind much either way but this was an IntelliJ recommendation. Type conflicts on imports usually lead to compile errors / symbol mismatches. Upstream Ktor also uses star imports in their documentation and samples.

Comment (4brunu) [reply modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache:3]: Yes, I know, and kotlin client multiplatform also uses it.
But since kotlin cliente jvm doesn't use them I would prefer to keep it that way.
Although this is something that may eventually change in future, because there is no obvious right or wrong answer here.

Comment (saschpe) [reply modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache]: IntelliJ disagrees, with the current code, it displays multiple unused import warnings in various files...

**Comment by 4brunu** [comment]
Can you please run to try to fix CI?
```
./mvnw clean package 
./bin/generate-samples.sh
./bin/utils/export_docs_generators.sh
```
Thanks

**Comment by 4brunu** [comment]
@saschpe could you please fix the merge conflicts with the master branch please?

**Comment by saschpe** [comment]
> @saschpe could you please fix the merge conflicts with the master branch please?

Done. Not sure about the recent Travis-CI error though

**Comment by wing328** [comment]
@saschpe thanks for the PR. When I ran `gradle wrapper && ./gradlew build -x test` in `samples/client/petstore/kotlin`, I got the following errors:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/williamcheng/Code/openapi-generator/samples/client/petstore/kotlin/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating root project 'kotlin-petstore-client'.
> Could not find method compile() for arguments [org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

While the same command runs fine in the master. I wonder if you can take another look to see if you can reproduce the issue.

**Comment by saschpe** [comment]
@wing328 Sure, I'll take another look soon.

**Comment by saschpe** [comment]
> @wing328 Sure, I'll take another look soon.

Should be fixed now

**Comment by 4brunu** [comment]
CI failures now are not related to this PR.

**Comment by wing328** [comment]
No luck. Still got the same error:
```
$ gradle wrapper

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/williamcheng/Code/openapi-generator2/samples/client/petstore/kotlin/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating root project 'kotlin-petstore-client'.
> Could not find method compile() for arguments [org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

```

Does it work for you locally?

**Comment by 4brunu** [comment]
Maybe the gradle version also needs to be updated?

**Comment by wing328** [comment]
I'm using 7.0.2:
```
$ gradle -version

------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7)
OS:           Mac OS X 11.2.3 x86_64

```

Can you also test it locally to see if it works for you?
```
git checkout -b saschpe-kotlin-client-gson master
git pull https://github.com/saschpe/openapi-generator.git kotlin-client-gson
```

**Comment by 4brunu** [comment]
I tried in my machine using gradle wrapper and it works.
```
./gradlew build -x test
```

So it may be an issue with gradle version 7.X, but I think it's recommended to use the gradle wrapper.

**Comment by saschpe** [comment]
Yes, `gradle wrapper` uses whatever Gradle version the system provides. The Gradle wrapper is almost always the better choice.

**Comment by 4brunu** [comment]
I can fix the compatibility with gradle 7.X in a different PR.
It's basically replacing `compile´ with `implementation`, `testCompile` with `testImplementation` and so on.
But this is an old issue.

**Comment by wing328** [comment]
If you look at the error message above. I simply ran `gradle wrapper` to start with and got the error message right away. Am I using gradle correctly by running `gradle wrapper` to being with?

**Comment by 4brunu** [comment]
Try to use the following command `./gradlew build -x test`

**Comment by 4brunu** [comment]
The problem is that you are using gradle 7.X to try to download the gradle wrapper, but the gradle 7.X looks at the `build.gradle` file and see the use of removed API's and show that error message.
I will create a PR to fix this, shortly after this PR is merged.

**Comment by wing328** [comment]
👌

**Comment by 4brunu** [comment]
To add more onto this, the gradle wrapper is always copied together with the generated code, so there is no need to download it, you can just use it straight away.

**Comment by wing328** [comment]
Previously there was an issue caught by the CI that we need to run `gradle wrapper` before running `./gradlew build -x test`.

**Comment by 4brunu** [comment]
Oh, I see, thanks for let me know 👍
