### PR TITLE
[kotlin]Fix ktor doesn't generate nullable types

### LINKED ISSUE #5198: kotlin-server/ktor doesn't generate nullable types
##### Description

The kotlin-server/ Ktor generator generates a `Path.kt` file that doesn't mark optional parameters as nullable.

##### openapi-generator version

openapi-generator-cli/4.2.3

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 0.0.1
  title: Optional Parameter Demo
paths:
  /foo:
    get:
      parameters:
        - in: query
          name: optional
          schema:
            type: integer
        - in: query
          name: mandatory
          required: true
          schema:
            type: integer
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: integer
```

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i demo.yaml -g kotlin-server -o test/`

##### Steps to reproduce

 1. Run the above command on the declaration file provided

This will generate the following template:

```kotlin
/**
* Optional Parameter Demo
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 0.0.1
*
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.server

import io.ktor.locations.KtorExperimentalLocationsAPI
import io.ktor.locations.Location

object Paths {
    /**
     *
     *
     * @param mandatory
     * @param optional  (optional)
     */
    @KtorExperimentalLocationsAPI
    @Location("/foo") class fooGet(val mandatory: kotlin.Int, val optional: kotlin.Int)

}
```

Optional parameters are not annotated as nullable (`?`).

##### Suggest a fix/enhancement

[Paths.kt.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache#L18) should be ammended to print `?` for optional parameters.

### PR DESCRIPTION
**Pull request by yutaka0m**
fixes #5198

Optional parameters have to annotated as nullable

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

I can't find `./bin/openapi3/kotlin-server-petstore.sh`:cry:

### CODE REVIEW

**Comment by yutaka0m** [comment]
@jimschubert (2017/09) ❤️, @dr4ke616 (2018/08) @karismann (2019/03) @Zomzog (2019/04) @andrewemery (2019/10) @4brunu (2019/11)

**Comment by ackintosh** [comment]
Restarted the TravisCI job.

**Comment by ackintosh** [comment]
If no one has further feedback, I'll merge this tomorrow.

File: modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache [hunk 1]
```diff
@@ -18,7 +18,7 @@ object Paths {
      {{#allParams}}* @param {{paramName}} {{description}} {{^required}}(optional{{#defaultValue}}, default to {{{.}}}{{/defaultValue}}){{/required}}
      {{/allParams}}*/
     @KtorExperimentalLocationsAPI
-    @Location("{{path}}") class {{operationId}}({{#allParams}}val {{paramName}}: {{{dataType}}}{{#hasMore}}, {{/hasMore}}{{/allParams}})
+    @Location("{{path}}") class {{operationId}}({{#allParams}}val {{paramName}}: {{{dataType}}}{{^required}}? = null{{/required}}{{#hasMore}}, {{/hasMore}}{{/allParams}})
```
Comment (4brunu) [inline modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache]: Maybe we should also check for {{#isNullable}}?{{/isNullable}}

Comment (yutaka0m) [reply modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache]: Thank you for reviewing!!

How is this? -> 

```suggestion
    @Location("{{path}}") class {{operationId}}({{#allParams}}val {{paramName}}: {{{dataType}}}{{#isNullable}}?{{/isNullable}}{{^isNullable}}{{^required}}? = null{{/required}}{{/isNullable}}{{#hasMore}}, {{/hasMore}}{{/allParams}})
```


I couldn't test because I don't know how to send `null` in query parameters.

Comment (4brunu) [reply modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache]: What about something like this?

`@Location("{{path}}") class {{operationId}}({{#allParams}}val {{paramName}}: {{{dataType}}}{{#isNullable}}?{{^required}} = null{{/required}}{{/isNullable}}{{^isNullable}}{{^required}}? = null{{/required}}{{/isNullable}}{{#hasMore}}, {{/hasMore}}{{/allParams}})`

Comment (jimschubert) [inline modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache]: I think required would have to append `?` if it's nullable, but this would change assignment in the method body not just in the parameter list. Also, rather than assigning `null` I think we'd want to honor defaults. For example, `i: Int? = 1` would be a valid argument.

Comment (4brunu) [reply modules/openapi-generator/src/main/resources/kotlin-server/libraries/ktor/Paths.kt.mustache]: I think this is a bit dangerous, because is a valid value that can be used without the user noticing.

**Comment by yutaka0m** [comment]
@jimschubert @4brunu 
Thank you for reviewing!!!

I added `?` when parameter is `required` and `isNullable`. (@4brunu reccomentded it)

**Comment by 4brunu** [comment]
Looks good to me 👍

**Comment by wing328** [comment]
@yutaka0m thanks for the PR, which has been included in the 4.3.0 release: https://twitter.com/oas_generator/status/1243455743937789952
