### PR TITLE
[Java][Native] Remove Javadoc warnings. fix #8692

### LINKED ISSUE #8692: [Java][Native] remove the warnings
##### Description

Found the following warning in the Java native client:
```
[WARNING] Javadoc Warnings
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java:63: warning: no @return
[WARNING] public static Class<?> getClassForElement(JsonNode node, Class<?> modelClass) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java:168: warning: no @param for visitedClasses
[WARNING] public static boolean isInstanceOf(Class<?> modelClass, Object inst, Set<Class<?>> visitedClasses) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/JSON.java:168: warning: no @return
[WARNING] public static boolean isInstanceOf(Class<?> modelClass, Object inst, Set<Class<?>> visitedClasses) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:84: warning: no @return
[WARNING] public CompletableFuture<Void> createXmlItem(XmlItem xmlItem) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:519: warning: no @return
[WARNING] public CompletableFuture<Void> testBodyWithFileSchema(FileSchemaTestClass body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:599: warning: no @return
[WARNING] public CompletableFuture<Void> testBodyWithQueryParams(String query, User body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:798: warning: no @return
[WARNING] public CompletableFuture<Void> testEndpointParameters(BigDecimal number, Double _double, String patternWithoutDelimiter, byte[] _byte, Integer integer, Integer int32, Long int64, Float _float, String string, File binary, LocalDate date, OffsetDateTime dateTime, String password, String paramCallback) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:903: warning: no @return
[WARNING] public CompletableFuture<Void> testEnumParameters(List<String> enumHeaderStringArray, String enumHeaderString, List<String> enumQueryStringArray, String enumQueryString, Integer enumQueryInteger, Double enumQueryDouble, List<String> enumFormStringArray, String enumFormString) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:997: warning: no @return
[WARNING] public CompletableFuture<Void> testGroupParameters(APItestGroupParametersRequest apiRequest) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1035: warning: no @return
[WARNING] public CompletableFuture<Void> testGroupParameters(Integer requiredStringGroup, Boolean requiredBooleanGroup, Long requiredInt64Group, Integer stringGroup, Boolean booleanGroup, Long int64Group) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1216: warning: no @return
[WARNING] public CompletableFuture<Void> testInlineAdditionalProperties(Map<String, String> param) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1296: warning: no @return
[WARNING] public CompletableFuture<Void> testJsonFormData(String param, String param2) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/FakeApi.java:1378: warning: no @return
[WARNING] public CompletableFuture<Void> testQueryParameterCollectionFormat(List<String> pipe, List<String> ioutil, List<String> http, List<String> url, List<String> context) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:79: warning: no @return
[WARNING] public CompletableFuture<Void> addPet(Pet body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:159: warning: no @return
[WARNING] public CompletableFuture<Void> deletePet(Long petId, String apiKey) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:521: warning: no @return
[WARNING] public CompletableFuture<Void> updatePet(Pet body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:602: warning: no @return
[WARNING] public CompletableFuture<Void> updatePetWithForm(Long petId, String name, String status) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/StoreApi.java:76: warning: no @return
[WARNING] public CompletableFuture<Void> deleteOrder(String orderId) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:76: warning: no @return
[WARNING] public CompletableFuture<Void> createUser(User body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:155: warning: no @return
[WARNING] public CompletableFuture<Void> createUsersWithArrayInput(List<User> body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:234: warning: no @return
[WARNING] public CompletableFuture<Void> createUsersWithListInput(List<User> body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:313: warning: no @return
[WARNING] public CompletableFuture<Void> deleteUser(String username) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:577: warning: no @return
[WARNING] public CompletableFuture<Void> logoutUser() throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/UserApi.java:646: warning: no @return
[WARNING] public CompletableFuture<Void> updateUser(String username, User body) throws ApiException {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:83: warning: no @param for key
[WARNING] public AdditionalPropertiesAnyType putAdditionalProperty(String key, Object value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:83: warning: no @param for value
[WARNING] public AdditionalPropertiesAnyType putAdditionalProperty(String key, Object value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:83: warning: no @return
[WARNING] public AdditionalPropertiesAnyType putAdditionalProperty(String key, Object value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:95: warning: no @return
[WARNING] public Map<String, Object> getAdditionalProperties() {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:102: warning: no @param for key
[WARNING] public Object getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesAnyType.java:102: warning: no @return
[WARNING] public Object getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java:84: warning: no @param for key
[WARNING] public AdditionalPropertiesArray putAdditionalProperty(String key, List value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java:84: warning: no @param for value
[WARNING] public AdditionalPropertiesArray putAdditionalProperty(String key, List value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java:84: warning: no @return
[WARNING] public AdditionalPropertiesArray putAdditionalProperty(String key, List value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java:96: warning: no @return
[WARNING] public Map<String, List> getAdditionalProperties() {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java:103: warning: no @param for key
[WARNING] public List getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesArray.java:103: warning: no @return
[WARNING] public List getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java:83: warning: no @param for key
[WARNING] public AdditionalPropertiesBoolean putAdditionalProperty(String key, Boolean value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java:83: warning: no @param for value
[WARNING] public AdditionalPropertiesBoolean putAdditionalProperty(String key, Boolean value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java:83: warning: no @return
[WARNING] public AdditionalPropertiesBoolean putAdditionalProperty(String key, Boolean value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java:95: warning: no @return
[WARNING] public Map<String, Boolean> getAdditionalProperties() {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java:102: warning: no @param for key
[WARNING] public Boolean getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesBoolean.java:102: warning: no @return
[WARNING] public Boolean getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java:83: warning: no @param for key
[WARNING] public AdditionalPropertiesInteger putAdditionalProperty(String key, Integer value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java:83: warning: no @param for value
[WARNING] public AdditionalPropertiesInteger putAdditionalProperty(String key, Integer value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java:83: warning: no @return
[WARNING] public AdditionalPropertiesInteger putAdditionalProperty(String key, Integer value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java:95: warning: no @return
[WARNING] public Map<String, Integer> getAdditionalProperties() {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java:102: warning: no @param for key
[WARNING] public Integer getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesInteger.java:102: warning: no @return
[WARNING] public Integer getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java:84: warning: no @param for key
[WARNING] public AdditionalPropertiesNumber putAdditionalProperty(String key, BigDecimal value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java:84: warning: no @param for value
[WARNING] public AdditionalPropertiesNumber putAdditionalProperty(String key, BigDecimal value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java:84: warning: no @return
[WARNING] public AdditionalPropertiesNumber putAdditionalProperty(String key, BigDecimal value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java:96: warning: no @return
[WARNING] public Map<String, BigDecimal> getAdditionalProperties() {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java:103: warning: no @param for key
[WARNING] public BigDecimal getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesNumber.java:103: warning: no @return
[WARNING] public BigDecimal getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java:83: warning: no @param for key
[WARNING] public AdditionalPropertiesObject putAdditionalProperty(String key, Map value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java:83: warning: no @param for value
[WARNING] public AdditionalPropertiesObject putAdditionalProperty(String key, Map value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java:83: warning: no @return
[WARNING] public AdditionalPropertiesObject putAdditionalProperty(String key, Map value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java:95: warning: no @return
[WARNING] public Map<String, Map> getAdditionalProperties() {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java:102: warning: no @param for key
[WARNING] public Map getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesObject.java:102: warning: no @return
[WARNING] public Map getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java:83: warning: no @param for key
[WARNING] public AdditionalPropertiesString putAdditionalProperty(String key, String value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java:83: warning: no @param for value
[WARNING] public AdditionalPropertiesString putAdditionalProperty(String key, String value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java:83: warning: no @return
[WARNING] public AdditionalPropertiesString putAdditionalProperty(String key, String value) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java:95: warning: no @return
[WARNING] public Map<String, String> getAdditionalProperties() {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java:102: warning: no @param for key
[WARNING] public String getAdditionalProperty(String key) {
[WARNING] ^
[WARNING] /private/var/tmp/openapi-generator/samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/model/AdditionalPropertiesString.java:102: warning: no @return
[WARNING] public String getAdditionalProperty(String key) {
[WARNING] ^
```

##### openapi-generator version

Latest master

##### OpenAPI declaration file content or url

Petstore

##### Steps to reproduce

```
mvn integration-test -f samples/client/petstore/java/native-async/pom.xml
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/8554

##### Suggest a fix

Will need to update the mustache templates to fix these issues

### PR DESCRIPTION
**Pull request by mikkomaunu**
Remove Javadoc warnings. fix #8692. 
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files.

### CODE REVIEW

File: samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java [hunk 1]
```diff
@@ -165,6 +166,7 @@ private String formatExceptionMessage(String operationId, int statusCode, String
    * 
    * @param petId Pet id to delete (required)
    * @param apiKey  (optional)
+   * @return CompletableFuture&lt;Void&gt;
```
Comment (wing328) [inline samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:169]: What about using `{{{...}}}` (original value) instead of `{{..}}` (HTML escaped)?

Comment (mikkomaunu) [reply samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:169]: Unfortunately I do not fully understand requested change. Can you please describe more in detail? 
We do not have value in hand and I assume in the end we want to have `&lt;` and not the `<`.

Comment (wing328) [reply samples/client/petstore/java/native-async/src/main/java/org/openapitools/client/api/PetApi.java:169]: Sorry. I was confused with C# doc in the code. The change looks good. Thanks for the PR.
