### PR TITLE
Fix inheritance with modelPrefix

### LINKED ISSUE #3150: [BUG] Model name prefix brakes model inheritance
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When generating for a YAML containing model composition / inheritance (for example the petstore-with-fake-endpoints-models-for-testing.yaml, see link below) **and** using the `--model-name-prefix` CLI parameter for setting a custom prefix for the generated models, the inheritance is not paid respect to correctly.

To stay with the example: Instead of only generating the fields and methods for className and color only in the MyPrefixAnimal class, it is generating both in the MyPrefixAnimal class and in its subclasses MyPrefixDog and MyPrefixCat. If one ommits the prefix CLI parameter, everything works fine and the fields and methods will be generated only where they are meaningful.

##### openapi-generator version

I tested it with 4.0.0, 4.1.0-SNAPSHOT and 5.0.0-SNAPSHOT and various generators (jaxrs-jersey, jaxrs-cxf, python) and was able to observe the problem in all cases.

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml

##### Command line used for generation

`java -jar openapi-generator-cli-4.0.0.jar generate -i petstore-with-fake-endpoints-models-for-testing.yaml -g jaxrs-jersey -o wrongInheritance --model-name-prefix MyPrefix`

##### Steps to reproduce

Use the command line above with the example from the repo and the generated MyPrefixCat model will be wrong.

### PR DESCRIPTION
**Pull request by Zomzog**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Check if inheritance parent exists with refName and not modelName. 

I've done it on DefaultCodegen so it will impact all generators.

Fix #3150

@wing328
@jimschubert
@cbornet
@ackintosh
@jmini
@etherealjoy

### CODE REVIEW

**Comment by ZwoCa** [comment]
@Zomzog Thank you, I just freshly built from your branch and can confirm this solves the problem.

Unfortunately, I'm not sure what's up with CircleCI. Seems like there was a problem unpacking some pre-requirements for the Hashkell test suite.

File: modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java [hunk 1]
```diff
@@ -654,4 +660,48 @@ public void mapParamImportInnerObject() {
...
+        OpenAPI openAPI = new OpenAPIParser()
+                .readLocation("src/test/resources/3_0/generic.yaml", null, new ParseOptions()).getOpenAPI();
+        codegen.setOpenAPI(openAPI);
+
+        CodegenModel codegenModel = codegen.fromModel("Dog", openAPI.getComponents().getSchemas().get("Dog"));
+
+        Assert.assertEquals(codegenModel.vars.size(), 1);
+    }
+    @Test
+    public void modelWithSuffuxDoNotContainInheritedVars() {
```
Comment (tkalliom) [inline modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java]: There is a typo: ”Suffux” vs. ”Suffix”

Comment (Zomzog) [reply modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java]: Fix thanks

**Comment by wing328** [comment]
cc @OpenAPITools/generator-core-team
