### PR TITLE
[Apex] Set namedCredential file name from the property

### LINKED ISSUE #2904: [BUG] Apex named credential property does not work
##### Description

When generating an apex client, the namedCredential property does not override the name of the named credential. In code, it looks like this property is ignored, and the 

##### openapi-generator version

4.0.0

##### Command line used for generation

```
openapi-generator generate -i https://directplus.documentation.dnb.com/assets/APIs/searchCriteria.json -g apex --additional-properties namedCredential=DnB_Direct
```

##### Suggest a fix

It looks like the name for the file is pulled from `openAPI.getInfo().getTitle()` rather than reading from the namedCredential property. Should be an easy fix to read the property instead.

https://github.com/OpenAPITools/openapi-generator/blob/046db19a8590f3557ae1e04be75792bbeb39cb69/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java#L164-L171

### PR DESCRIPTION
**Pull request by loganm**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`. If contributing template-only or documentation-only changes which will change sample output, be sure to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) first.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.1.x`, `5.0.x`. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

@asnelling It seems like you're the person to review this one.

This fixes #2904

The namedCredential property is intended to override the namedCredentials name, but it wasn't being used. Instead, the title from the openapi spec file was used in all cases, and the namedCredential property wasn't used anywhere.

If a namedCredential property is provided, it will be used instead of the default name. For backwards compatibility, the spec title is still used for the named credential by default.

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java [hunk 1]
```diff
@@ -161,8 +161,10 @@ public void processOpts() {
 
     @Override
     public void preprocessOpenAPI(OpenAPI openAPI) {
-        Info info = openAPI.getInfo();
-        String calloutLabel = info.getTitle();
+        String calloutLabel = openAPI.getInfo().getTitle();
+        if (namedCredential != null && !namedCredential.trim().isEmpty()) {
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java]: What about using `StringUtils.isNotEmpty` instead?

Comment (loganm) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java]: @wing328 Very good idea. I'm not a Java developer by trade, so I'm a bit gun shy with libraries.

**Comment by wing328** [comment]
cc @muenzpraeger

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java [hunk 2]
```diff
@@ -46,7 +47,7 @@
     private String classPrefix = "OAS";
     private String apiVersion = "42.0";
     private String buildMethod = "sfdx";
-    private String namedCredential = classPrefix;
+    private String namedCredential;
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java]: @loganm What about keeping the default as `classPrefix`?

Comment (loganm) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java]: The current behaviour of the generator is to use the spec title for the namedCredential. For example, I'm using a Dun and Bradstreet spec with the title 'Search_for_a_Company_or_Contact'.

The default classPrefix is 'OAS' which doesn't mean much. The spec title is more informative about purpose of the named credential.

Now that the namedCredential var is being referenced, leaving the default value as classPrefix here would also change the default behaviour of the generator. It could be a breaking change for anyone using it presently.


Do you think it's possible to get at the spec title as the default here instead of the class prefix?

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java]: > Now that the namedCredential var is being referenced, leaving the default value as classPrefix here would also change the default behavior of the generator. It could be a breaking change for anyone using it presently.

Yes, we're on the same page to make this change backward-compatible.

Let me review again as I thought the default value is no longer the same.

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ApexClientCodegen.java]: I just updated the petstore samples and I can see the issue you've fixed in this PR 👍

**Comment by wing328** [comment]
I've updated the Apex samples and add apex-petstore.sh to ensure-up-to-date script via 5ad318bfae

**Comment by wing328** [comment]
@loganm thanks again for your contribution, which has been included in the v4.0.1 release (https://twitter.com/oas_generator/status/1135534738658062336)
