### PR TITLE
typescript-fetch: Only generate npm package if npmName specified

### LINKED ISSUE #3694: [BUG][typescript-fetch] Output is now nested in a "src" folder which breaks typescript package references
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Changes in [this commit](https://github.com/OpenAPITools/openapi-generator/commit/9e659d13ed42faa2f630511deac8f3230f74c82a#diff-b6db0f9dfdf7043aa45fbeb47131dcebL54) introduced several related bugs. 

1. Output is now partially nested within a new `src` folder.
2. package.json.mustache was not updated to reflect this change
3. breaks anyone who was using local npm package references with typescript to avoid creating a separate `/dist` folder for the generated client code.

##### openapi-generator version

v4.0.3 => v4.1.0

##### Suggest a fix

- Revert the folder name change.
- Add a flag to opt in or out of the new `src` folder 
- Update the mustache templates accordingly.

### PR DESCRIPTION
**Pull request by rob-deutsch**
typescript-fetch will only generate the NPM package infrastructure if npmName is specified. (Related to #3403)

Fixes #3694

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07)

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

File: samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ import {
 } from '../models';
 
 export interface AddPetRequest {
-    body: Pet;
+    pet: Pet;
```
Comment (rob-deutsch) [inline samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts]: This seems odd, but I don't know why this would've/could've changed. Any suggestions?

Comment (rob-deutsch) [reply samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts]: This is because I accidentally committed the openapi3 samples. Resolved.

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java [hunk 2]
```diff
@@ -54,8 +54,14 @@ public TypeScriptFetchClientCodegen() {
         outputFolder = "generated-code/typescript-fetch";
         embeddedTemplateDir = templateDir = "typescript-fetch";
 
-        this.apiPackage = "src" + File.separator +"apis";
-        this.modelPackage = "src" + File.separator + "models";
+        if (additionalProperties.containsKey(NPM_NAME)) {
```
Comment (rob-deutsch) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java]: It seems like I cannot access additionalProperties in the class constructor. Any suggestions about a better way to do this?

Comment (rob-deutsch) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java]: Resolved: This can be handled in processOpts()

**Comment by rob-deutsch** [comment]
Thanks @macjohnny, it took me a few goes to get it right, but I got there eventually!

**Comment by wing328** [comment]
@rob-deutsch  thanks for the PR, which has been included in the v4.2.1 release: https://twitter.com/oas_generator/status/1195339336922759168
