### PR TITLE
Log Warn Messages for ineffective Schema Validations, updated

### LINKED ISSUE #6491: [REQ][validate] Warn for validation keyword type mismatch
Currently `validate` does not warn if JSON Schema validation keywords are applied to schemas with types for which the validation keyword has no effect.  For example:

```yaml
openapi: '3.0.3'
info:
  title: Incorrect validation keyword example
  version: '1.0.0'
components:
  schemas:
    Vector3:
      type: array
      items:
        type: number
      maxLength: 3
      minLength: 3
paths:
  /location:
    get:
      operationId: getLocation
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vector3'
```

`openapi-generator-cli.jar validate -i openapi.yaml` produces:

    Validating spec (openapi.yaml)
    No validation issues detected.

However, `maxLength`/`minLength` validate the length of strings and have no effect on `Vector3`, which has `type: array`.  The author likely intended to use `maxItems`/`minItems`.

Is there any chance you'd consider producing a warning for such cases?

Thanks for considering,
Kevin

### PR DESCRIPTION
**Pull request by martin-mfg**
### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- `[ ]` ~~Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:~~ (*some tests fail already on master branch*)
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)

-----------

close #6491

This PR is based on [chidambaranadig](https://github.com/chidambaranadig)'s commits in #12314. On top of their changes, I ...
- adressed the remaining code review comments from #12314
- updated the added `logback-classic` dependency
- merged the `master` branch to resolve merge conflicts

### CODE REVIEW

**Comment by wing328** [comment]
can you please resolve the merge conflicts when you've time?

**Comment by martin-mfg** [comment]
@wing328 done :-)

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java [hunk 1]
```diff
@@ -371,12 +372,6 @@ private static void visitSchema(OpenAPI openAPI, Schema schema, String mimeType,
         }
     }
 
-    @FunctionalInterface
-    private static interface OpenAPISchemaVisitor {
-
-        public void visit(Schema schema, String mimeType);
-    }
-
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java:379]: @martin-mfg do you know why this is removed? Is it because it's not being used at the moment?

(not saying we need to keep this)

cc @OpenAPITools/generator-core-team

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java:379]: let's go ahead with this. we can always add it back later if there's a valid use case for this as it was added back in 2018.

Comment (martin-mfg) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java:379]: It's not really removed, but it is moved down to line 1964.
