### PR TITLE
[Slim] Fix AbstractAuthenticator constructor TypeError

### LINKED ISSUE #2640: [BUG] PHPSlim Auth middleware TypeError
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
Current generator requires `AbstractAuthenticator` user implementation when schema contains security definitions. When implementation class is provided app throws TypeError.

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

Any spec file file with secured endpoints can reproduce the bug.
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

##### Command line used for generation

```shell
bin/php-slim-server-petstore.sh
```

##### Steps to reproduce

1. Generate server stubs with any spec file with secured endpoints
2. Make HTTP request to any secured endpoint
3. App throws Exception with message
```
How about extending AbstractAuthenticator class by OpenAPIServer\\Auth\\OAuthAuthenticator?
```
4. Overwrite `AbstractAuthenticator` with your own `OAuthAuthenticator` class.
5. Generate new Composer autoload with `composer dump-autoload`
6. Make the same HTTP request to any secured endpoint.
7. App throws error
```
[10-Apr-2019 17:42:41 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to OpenAPIServer\Auth\AbstractAuthenticator::__construct() 
must implement interface Psr\Container\ContainerInterface, array given, called in 
/Applications/MAMP/htdocs/openapi-generator/samples/server/petstore/php-slim/lib/SlimRouter.php on line 650 and defined in 
/Applications/MAMP/htdocs/openapi-generator/samples/server/petstore/php-slim/lib/Auth/AbstractAuthenticator.php:70
```

##### Suggest a fix

Will fix it myself.

### PR DESCRIPTION
**Pull request by ybelenko**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Current generator requires `AbstractAuthenticator` user implementation when schema contains security definitions. When implementation class is provided app throws TypeError.

```
[10-Apr-2019 17:42:41 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to OpenAPIServer\Auth\AbstractAuthenticator::__construct() 
must implement interface Psr\Container\ContainerInterface, array given, called in 
/Applications/MAMP/htdocs/openapi-generator/samples/server/petstore/php-slim/lib/SlimRouter.php on line 650 and defined in 
/Applications/MAMP/htdocs/openapi-generator/samples/server/petstore/php-slim/lib/Auth/AbstractAuthenticator.php:70
```

Fixes #2640 

cc @jebentier, @dkarlovi, @mandrean, @jfastnacht, @ackintosh, @ybelenko, @renepardon

### CODE REVIEW

File: samples/server/petstore/php-slim/lib/SlimRouter.php [hunk 1]
```diff
@@ -586,6 +586,9 @@ public function __construct($container = [])
     {
         $this->slimApp = new App($container);
 
+        // middlewares requires Psr\Container\ContainerInterface instead of array
+        $container = $this->slimApp->getContainer();
+
```
Comment (wing328) [inline samples/server/petstore/php-slim/lib/SlimRouter.php]: @ybelenko What about updating the method signature as well? e.g.
```
    public function __construct($appContainer = [])
    {
        $this->slimApp = new App($appContainer);
```

Comment (ybelenko) [reply samples/server/petstore/php-slim/lib/SlimRouter.php]: @wing328 
Here is the thing, `new App(array $container = [])` constructor accepts array or `ContainerInterface`, but `App->getCongainer(): Psr\Container\ContainerInterface` method always returns `ContainerInnterface`. Slim Framework magic. :smile:

By the way, my biggest goal is to make specifically this class(`SlimRouter.php`) to be untoched by user. I think that file should be kind of library/internal, in perfect world/scenario user should not edit this file. When I will achieve this, comments and variable names will not be important anymore.

I try my best to store all user preferences and configs only within one file:
https://github.com/OpenAPITools/openapi-generator/blob/821fa40afc677523fdfb3781c3d48802f7236b56/samples/server/petstore/php-slim/index.php#L17-L28

Comment (wing328) [reply samples/server/petstore/php-slim/lib/SlimRouter.php]: > Slim Framework magic

Understood. My suggestion is more on readability of the code. When I first read it, I didn't know why $container is reassigned. That's why I suggest naming the method argument differently to make sure aware that $container may not be the same as the $appContainer in the method argument.

Comment (ybelenko) [reply samples/server/petstore/php-slim/lib/SlimRouter.php]: @wing328 
To make it more clear I would name it `$settings` or `$options` because input parameter technically it's not container yet. How is that sounds to you?

Comment (wing328) [reply samples/server/petstore/php-slim/lib/SlimRouter.php]: Sounds good to me 👍
