### PR TITLE
[typescript-nestjs-server] #22928 improve request parameter handling

### LINKED ISSUE #22928: [BUG] [typescript-nestjs-server] GET apis not parsed properly. Enum imports break and optionality not maintained
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

When generating NestJS typescript server stubs, parameters which are optional in the OpenAPI spec become required in the Typescript type created in the `.controller.ts` and `Api.ts` files. This is noticeable with GET endpoints specifically, where the request is not included in a `model.ts` file. Also, when enums are in the parameters, it breaks the import. I am using `useSingleRequestParameter=true` but it happens even if this is not set.

##### openapi-generator version

I am calling through the `openapi-generator-cli` npm package. Looks like 7.17.0 version

```json
{
  "$schema": "./node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "7.17.0"
  }
}
```

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Minimal Example API
  version: 1.0.0

paths:
  /items:
    get:
      summary: Get items
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string

        - name: description
          in: query
          required: false
          schema:
            type: string

        - name: quantity
          in: query
          required: false
          schema:
            type: integer
            minimum: 0

        - name: type
          in: query
          required: false
          schema:
            type: string
            enum:
              - basic
              - premium
              - enterprise

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    type:
                      type: string
```

##### Generation Details

Running the following from Node

```bash
openapi-generator-cli generate \
  -i ./openapi.yaml \
  -g typescript-nestjs-server \
  -o ./generated \
  --additional-properties=importFileExtension=.js,supportsES6=true,useSingleRequestParameter=true
```

##### Steps to reproduce

* Run the openapi-generator-cli with the example openapi spec. Notice it has a GET endpoint, as well as one parameter being an enum. This will output files, but there are a couple issues

 Here is the `Default.api.ts` file. Notice the issues importing with the enums. Also, all parameters have `required:false` explicitly in the spec (omitting had the same results), but the TS types do not have optionality included.

```ts
// DefaultApi.ts
import { Injectable } from '@nestjs/common';
import { Observable } from 'rxjs';
import { &#39;basic&#39; | &#39;premium&#39; | &#39;enterprise&#39;, ItemsGet200ResponseInner,  } from '../models/index.js';

export type ItemsGetRequestParams = {
    name: string
    description: string
    quantity: number
    type: 'basic' | 'premium' | 'enterprise'
}

@Injectable()
export abstract class DefaultApi {
  abstract itemsGet(itemsGetRequestParams: ItemsGetRequestParams, request: Request): Array<ItemsGet200ResponseInner> | Promise<Array<ItemsGet200ResponseInner>> | Observable<Array<ItemsGet200ResponseInner>>;
} 
```

The .controller file is similar issues.

```ts
// DefaultApi.controller.ts
import { Body, Controller, Get, Param, Query, Req } from '@nestjs/common';
import { Observable } from 'rxjs';
import { DefaultApi } from '../api/index.js';
import { &#39;basic&#39; | &#39;premium&#39; | &#39;enterprise&#39;, ItemsGet200ResponseInner,  } from '../models/index.js';

@Controller()
export class DefaultApiController {
  constructor(private readonly defaultApi: DefaultApi) {}

  @Get('/items')
  itemsGet(@Query('name') name: string, @Query('description') description: string, @Query('quantity') quantity: number, @Query('type') type: 'basic' | 'premium' | 'enterprise', @Req() request: Request): Array<ItemsGet200ResponseInner> | Promise<Array<ItemsGet200ResponseInner>> | Observable<Array<ItemsGet200ResponseInner>> {
    return this.defaultApi.itemsGet({ name, description, quantity, type, }, request);
  }

} 
```

##### Related issues/PRs

Similar issue in another template/plugin - https://github.com/OpenAPITools/openapi-generator/issues/18191  

##### Suggest a fix

These mustache templates seem to have bugs, which include not maintaining optional/non-required types

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-nestjs-server/api.mustache#L10C23-L10C31

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-nestjs-server/api.mustache#L10C23-L10C31

### PR DESCRIPTION
**Pull request by aryobenholzner**
addresses #22928

- remove incorrect inline enum import
- correctly handle required and nullable specs
- add additional tests by generating server for `parameter-test-spec.yaml` to correctly handle various parameter types

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package || exit
  ./bin/generate-samples.sh ./bin/configs/*.yaml || exit
  ./bin/utils/export_docs_generators.sh || exit
  ``` 
  (For Windows users, please run the script in [WSL](https://learn.microsoft.com/en-us/windows/wsl/install))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR solves a reported issue, reference it using [GitHub's linking syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) (e.g., having `"fixes #123"` present in the PR description)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11) @amakhrov (2020/02) @davidgamero (2022/03) @mkusaka (2022/04) @joscha (2024/10) @dennisameling (2026/02)
@wing328 

---
## Summary by cubic
Improves request parameter handling in the TypeScript NestJS server generator to fix #22928. Adds schema defaults, numeric parsing with pipes, header/cookie decorators, strict null/undefined typing, and safer imports.

- New Features
  - Custom `@Headers` decorator (lowercase lookups + pipe support) and generated `@Cookies` decorator.
  - Apply schema defaults with `DefaultValuePipe`; add param sample + e2e tests from parameter-test-spec.yaml.
  - Generated API method/request-param types include null and undefined as per spec.
  - Docs: Express-only note, cookie setup using `cookie-parser`, and `ApiModule.forRoot({ apiImplementations, providers? })`.

- Bug Fixes
  - Correct types for required/optional/nullable params; normalize "undefined" defaults.
  - Parse numeric params with `ParseIntPipe`/`ParseFloatPipe`; pipes marked optional for non-required/nullable values.
  - Bind exact spec names via `baseName` in Param/Query/Headers/Cookies (supports `$`, dashes, etc.).
  - Import handling: skip inline union string literals and validate each union member before importing; clarified `tsVersion`/`rxjsVersion` docs.

<sup>Written for commit 387123d8d47c78642143c6b1f79905e0ae173fa1. Summary will update on new commits.</sup>

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNestjsServerCodegen.java [hunk 1]
```diff
@@ -274,7 +275,13 @@ private String applyLocalTypeMapping(String type) {
     }
 
     private boolean isLanguagePrimitive(String type) {
-        return languageSpecificPrimitives.contains(type);
+        return languageSpecificPrimitives.contains(type) || isInlineUnion(type);
+    }
+
+    private boolean isInlineUnion(String type) {
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNestjsServerCodegen.java:291]: please add docs with an example of the input

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/cookies-decorator.mustache [hunk 2]
```diff
@@ -0,0 +1,6 @@
+import { createParamDecorator, ExecutionContext } from '@nestjs/common';
+
+export const Cookies = createParamDecorator((data: string, ctx: ExecutionContext) => {
+const request = ctx.switchToHttp().getRequest();
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/resources/typescript-nestjs-server/cookies-decorator.mustache]: please fix indentation

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/cookies-decorator.mustache [hunk 3]
```diff
@@ -0,0 +1,6 @@
+import { createParamDecorator, ExecutionContext } from '@nestjs/common';
+
+export const Cookies = createParamDecorator((data: string, ctx: ExecutionContext) => {
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/resources/typescript-nestjs-server/cookies-decorator.mustache]: please add docs here

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/controller.mustache [hunk 4]
```diff
@@ -1,7 +1,10 @@
-import { Body, Controller{{#httpMethods}}, {{.}}{{/httpMethods}}, Param, Query, Req } from '@nestjs/common';
+import { Body, Controller{{#httpMethods}}, {{.}}{{/httpMethods}}, Param, Query, Headers, Req } from '@nestjs/common';
 import { Observable } from 'rxjs';
+import { Cookies } from '../cookies-decorator';
```
[the remark this answers is not in the document]
Comment (aryobenholzner) [reply modules/openapi-generator/src/main/resources/typescript-nestjs-server/controller.mustache]: a `cookies-decorator.mustache` exists, which results in a generated `cookies-decorator.ts`. When importing from typescript modules the file extension is not required and normally omitted.

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/controller.mustache [hunk 5]
```diff
@@ -10,7 +13,7 @@ export class {{classname}}Controller {
...
+  {{operationId}}({{#allParams}}{{#isPathParam}}@Param('{{baseName}}') {{/isPathParam}}{{#isQueryParam}}@Query('{{baseName}}') {{/isQueryParam}}{{#isHeaderParam}}@Headers('{{baseName}}') {{/isHeaderParam}}{{#isCookieParam}}@Cookies('{{baseName}}') {{/isCookieParam}}{{#isBodyParam}}@Body() {{/isBodyParam}}{{paramName}}: {{{dataType}}}{{#isNullable}} | null{{/isNullable}}{{^required}} | undefined{{/required}}{{#defaultValue}} = {{{defaultValue}}}{{/defaultValue}}, {{/allParams}}@Req() request: Request): {{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}void{{/returnType}} | Promise<{{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}void{{/returnType}}> | Observable<{{#returnType}}{{{returnType}}}{{/returnType}}{{^returnType}}void{{/returnType}}> {
```
[the remark this answers is not in the document]
Comment (aryobenholzner) [reply modules/openapi-generator/src/main/resources/typescript-nestjs-server/controller.mustache]: should be addressed by https://github.com/OpenAPITools/openapi-generator/commit/bb85c065e6153a1f8089b3558d5a83ba2098d2eb

**Comment by aryobenholzner** [comment]
addressed nearly all of the feedback. the multipart and file upload requests should probably be a separate issue/PR as its not related to the original issue.

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/headers-decorator.mustache [hunk 6]
```diff
@@ -0,0 +1,16 @@
...
+* Workaround for enabling PipeTransformers on Headers (see https://github.com/nestjs/nest/issues/356)
+*
+* Usage:
+* ```
+* @Get()
+* findAll(@Headers('name') name: string) {}
+* ```
+*/
+export const Headers = createParamDecorator((data: string, ctx: ExecutionContext) => {
+const request = ctx.switchToHttp().getRequest();
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/resources/typescript-nestjs-server/headers-decorator.mustache]: please fix the indentation here

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/headers-decorator.mustache [hunk 7]
```diff
@@ -0,0 +1,16 @@
...
+* A decorator function for retrieving headers from the request object in an HTTP context.
+* Workaround for enabling PipeTransformers on Headers (see https://github.com/nestjs/nest/issues/356)
+*
+* Usage:
+* ```
+* @Get()
+* findAll(@Headers('name') name: string) {}
+* ```
+*/
+export const Headers = createParamDecorator((data: string, ctx: ExecutionContext) => {
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/resources/typescript-nestjs-server/headers-decorator.mustache]:
```suggestion
export const Headers = createParamDecorator((headerName: string, ctx: ExecutionContext) => {
```

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/cookies-decorator.mustache [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+*
+* Consult https://docs.nestjs.com/techniques/cookies for further information
+*
+* Usage:
+* ```
+* @Get()
+* findAll(@Cookies('name') name: string) {}
+* ```
+*/
+export const Cookies = createParamDecorator((data: string, ctx: ExecutionContext) => {
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/resources/typescript-nestjs-server/cookies-decorator.mustache]:
```suggestion
export const Cookies = createParamDecorator((cookieName: string, ctx: ExecutionContext) => {
```

**Review by macjohnny — COMMENTED** [review]
should we update the generated readme to indicate some additional imports/middleware are needed? or what exactly are users supposed to configure to make proper use of these changes?

**Comment by aryobenholzner** [comment]
> should we update the generated readme to indicate some additional imports/middleware are needed? or what exactly are users supposed to configure to make proper use of these changes?

I updated the README, I also updated the usage description to reflect the changes from #22403

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/README.md [hunk 9]
```diff
@@ -2,6 +2,8 @@
 
 Usage: The generated output is intended to be its own module, that can be imported into your NestJS App Module. You do not need to change generated files, just import the module and implement the API
 
+Currently, only Express is supported.
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/resources/typescript-nestjs-server/README.md:5]: was this already the case before this change?

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/README.md [hunk 10]
```diff
@@ -45,12 +47,35 @@ Example usage (with the openapi sample `petstore.yaml`):
...
 
-You now can regenerate the API module as often as you want without overriding your implementation.
\ No newline at end of file
+You now can regenerate the API module as often as you want without overriding your implementation.
+
+## Using Cookie parameters
+
+In order for cookie parameters to work, the the framework specific cookie middleware must be enabled.
+
+For Express, the `cookie-parser` middleware must be installed and enabled.
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/resources/typescript-nestjs-server/README.md]: please link the package/npm page here

File: modules/openapi-generator/src/main/resources/typescript-nestjs-server/README.md (hunk 9 above)
Comment (aryobenholzner) [reply modules/openapi-generator/src/main/resources/typescript-nestjs-server/README.md:5]: Fastify compability should not be any better or worse with this PR. Although some basic stuff might already work, I have never tested Fastify support.
 The controllers currently forward the  `Request` typed from express and from what I know Fastify has some specifics that might need different handling. That’s why I wanted to add the disclaimer until a generator option for Fastify exists where we can handle specifics, and have a test suite ensuring Fastify works properly.
