### PR TITLE
Fix composed oneof type 1749

### LINKED ISSUE #1749: [BUG] DefaultCodegen should generate OneOf<ObjA,ObjB> from composed-oneof, but got Oneof<ObjA>
##### Description

DefaultCodegen cannot generate composed oneof type properly. this generates the type which includes only first type of `Schema.oneOf`. 

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

`3_0/composed-oneof.yaml`

##### Command line used for generation

`./mvnw test`

##### Steps to reproduce

[DefaultCodegenTest.java:252](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/DefaultCodegenTest.java#L252)
the value of `type` is `oneOf<ObjA>`

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/1745

### PR DESCRIPTION
**Pull request by zigen**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

I fixed #1749

### CODE REVIEW

**Comment by wing328** [comment]
@zigen thanks for the fix, which has been merged into master.

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java [hunk 1]
```diff
@@ -1413,8 +1413,8 @@ public String getSchemaType(Schema schema) {
                         // primitive type or model
                         names.add(getAlias(getPrimitiveType(s)));
                     }
-                    return "oneOf<" + String.join(",", names) + ">";
                 }
+                return "oneOf<" + String.join(",", names) + ">";
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java]: @zigen thanks for the fix. I've filed a similar one to fix anyof: https://github.com/OpenAPITools/openapi-generator/pull/1750/files#diff-7cb46fa53f89a458a7b7cb201d2214a8R1399

Ref: https://github.com/OpenAPITools/openapi-generator/pull/1757/files

Comment (zigen) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java]: cool!!
thanks for fix.
