### PR TITLE
[BUG][KOTLIN] Sanitize names of the adapter variables in anyOf and oneOf model template to avoid compilation errors

### LINKED ISSUE #19942: [BUG] Kotlin generator: generateOneOfAnyOfWrappers=true leads to broken code
##### Description

While using the Kotlin generator in a Android Project with "generateOneOfAnyOfWrappers=true", the generator generates code with the Gson Library even tough it should be Moshi by default(?). After including the Gson Library to the project, it still failed. Partly because of invalid naming of variables. As you can see in the picture below, on line 37 and 38, the generates variables are interpreted by kotlin as extension functions. So this won't compile.

Bildschirmfoto 2024-10-22 um 12 02 06

To start from the beginning: We received a new OpenAPI Spec from our server team. The spec contains some "OneOf" relations. The file itself should be valid, since our iOS team was able to generate the desired code with `openapi-generator generate -i Common/MeteoMapsAPI/meteomapsapi.json -g swift5 -o Common/MeteoMapsAPI --model-name-prefix SRF --additional-properties=projectName=MeteoMapsAPI,generateAliasAsModel=true`. 
If we (Android team) run the generator without "generateOneOfAnyOfWrappers=true", an error get's thrown `@JsonClass can't be applied to ch.srf.meteo.data.meteomap.model.MeteoMapLayer: must be a Kotlin class`. This makes sense looking into the generated code:

Bildschirmfoto 2024-10-22 um 11 59 23

So I guess, the approach of using "generateOneOfAnyOfWrappers=true" should be correct?

The full OpenAPI declaration file can be found below.

##### openapi-generator version

7.9.0, 7.8.0

##### OpenAPI declaration file content or url

[meteomap-api.json](https://github.com/user-attachments/files/17473660/meteomap-api.json)

##### Generation Details

```
    val generateMeteoMap by registering(GenerateTask::class) {
        generatorName.set("kotlin")
        .....
        configOptions.set(apiConfigOptions)
        additionalProperties.set(
            mapOf(
                "enumPropertyNaming" to "UPPERCASE",
                "useCoroutines" to "true",
                "moshiCodeGen" to "true",
                "generateOneOfAnyOfWrappers" to "true",
            )
        )
        library.set("jvm-retrofit2")
    }
```

##### Steps to reproduce

If you run the generator either with Gradle or via CLI with the attached OpenAPI declaration file (which should be valid in my opinion), the error occures.

### PR DESCRIPTION
**Pull request by CaptainAye**
Pr introduces sanitizing of the adapter... names in the oneOf and anyOf model templates in order to avoid incorrect names being generated. 
The root cause of this issue comes from the fact that Kotlin generator uses canonical names for type mappings and thus {{dataType}} variable is a canonical name with dots. It is then used for variable names generation.
Sanitizing of the names will be enough to fix #19942 but the type mappings problem should also be addressed imo. 
It seems that other generators (i.e. java) are not having this issue.

During the preparation of this fix, I also realized that `validateJsonElement` methods are also missing in oneOf and anyOf classes, which would also cause the compilation errors. I fixed this issue as well in the scope of this pr.

Technical Kotlin Committee:
@dr4ke616 @karismann @Zomzog @andrewemery @4brunu @yutaka0m @stefankoppier @e5l

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming `7.x.0` minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

File: samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUserOrPetOrArrayString.kt [hunk 1]
```diff
@@ -147,4 +147,58 @@ data class ApiUserOrPetOrArrayString(var actualInstance: Any? = null) {
...
+
+    companion object {
+        /**
+        * Validates the JSON Element and throws an exception if issues found
+        *
+        * @param jsonElement JSON Element
+        * @throws IOException if the JSON Element is invalid with respect to ApiUserOrPetOrArrayString
+        */
+        @Throws(IOException::class)
+        fun validateJsonElement(jsonElement: JsonElement?) {
```
Comment (4brunu) [inline samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUserOrPetOrArrayString.kt:159]: @CaptainAye Thanks for this PR. 
I have one question, why is this jsonElement optional?
If a jsonElement is optional is invalid, or am I wrong?
If we really need to receive the jsonElement as optional, I think we should check if it's null and throw an exception as early as possible, to avoid the !! and required in this code, that can cause a runtime exception.

Comment (CaptainAye) [reply samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUserOrPetOrArrayString.kt:159]: I kept `jsonElement` optional in the definition to maintain compatibility with `validateJsonElement()` method in `src/main/resources/kotlin-client/data_class.mustache`. Idd it seems that the jsonElement could be just required in all of these places. I wanted to avoid broadening the scope of this pr.
I pushed the change to check that jsonElement isn't at the beginning of the method. 
Let me know if you think that's good enough.

Comment (4brunu) [reply samples/client/petstore/kotlin-model-prefix-type-mappings/src/main/kotlin/org/openapitools/client/models/ApiUserOrPetOrArrayString.kt:159]: Looks good to me 👍
