### PR TITLE
[javascript] fix docs example quoting, fixes #6324

### LINKED ISSUE #6324: [BUG] [JAVA] [JavaScript] Getting started example code with parameter examples produces invalid syntax
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Running the generator against a sample OpenApi 3.0 spec produces invalid example code in the getting started guide. I've tried this using both the Java and JavaScript generators and the same issue exists.

##### openapi-generator version

4.3.1
##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io
  - url: http://petstore-sandbox.swagger.io
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: x-api-key
          in: header
          description: API Key
          schema:
            type: string
            example: 5bb608a0-7711-4f0e-8b51-00cfa968e042
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

##### Command line used for generation

java -jar openapi-generator-cli.jar generate \
  --generator-name java \
  --output java \
  --library google-api-client \
  --input-spec ./petstore.yaml \
  --group-id io.swagger.petstore.client \
  --artifact-id io.swagger.petstore.client \
  --api-package io.swagger.petstore.client.api \
  --model-package io.swagger.petstore.client.model \
  --invoker-package io.swagger.petstore.client

##### Steps to reproduce

1. Run the code generator using command line above
2. Open the README.md in the generated `java` directory
3. Look for LOC that looks like this:

### PR DESCRIPTION
**Pull request by valpackett**
And prefer example over default

This is #2669 but for JavaScript.

@CodeNinjai @frol @cliffano

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java [hunk 1]
```diff
@@ -740,6 +742,24 @@ public void setParameterExampleValue(CodegenParameter p) {
...
+            Example example = parameter.getExamples().values().iterator().next();
+            if (example.getValue() != null) {
+                codegenParameter.example = example.getValue().toString();
+            }
+        } else if (schema != null && schema.getExample() != null) {
+            codegenParameter.example = schema.getExample().toString();
+        }
+
+        setParameterExampleValue(codegenParameter);
+    }
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java:761]: thanks for the PR. if you didn't add this code block, does it work for you?

default codegen seems doing that already: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2134-L2151

Comment (valpackett) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java:761]: The problem in the default codegen is that it has early `return;` statements that skip the call.

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavascriptClientCodegen.java:761]: ah ok. i'll try to review and get that fix
