### PR TITLE
[bug][maven] Fix custom windows classpaths in maven plugin

### LINKED ISSUE #4208: [BUG] [MVN Plugin] -   <templateDirectory> is ignored
I'm running mvn install with the following configuration - but the looks like the <templateDirectory> is ignored and Template directory always defaults to embedded dir.

Here is the maven plugin section in which the templateDirectory is ignored:
```
  <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.1.3</version>
                <executions>
                    <execution>
                        <id>swagger-generate-server-code</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.parent.parent.basedir}/src/main/resources/swagger-spec-pet-store.json</inputSpec>
                            <templateDirectory>${project.basedir}/src/main/resources</templateDirectory>
                            <modelPackage>com.computrade.restful.services.model</modelPackage>
                            <apiPackage>com.computrade.restful.services.server.api</apiPackage>
                            <invokerPackage>com.computrade.restful.services.server.invoker</invokerPackage>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <java8>true</java8>
                                <dateLibrary>java8</dateLibrary>
                                <skipDefaultInterface>true</skipDefaultInterface>
                            </configOptions>
                            <configHelp>false</configHelp>
                            <generatorName>spring</generatorName>
                            <library>spring-boot</library>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```
##### openapi-generator version

                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.1.3</version>

I tried also earlier  from 4.0.0 and above - but still the same.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/3364
I see this issue was closed. 
( but it wasn't open on the Maven plugin from the beginning )

Thanks, 
Yuval Ishay

### PR DESCRIPTION
**Pull request by jimschubert**
Fixes #4208 

Thanks to @DenisKnoepfle for the discussion around this bug to help reproduce the underlying issue.

* Updates WorkflowSettings to duplicate the logic which checks for classpath files (previously, would break on Windows, or on all OS if template directory did not match structures in openapi-generator's resource directory)
* Updates java-client.xml in Maven example to allow spot-check of `templateDirectory` property
* Fixes classpath check in template manager to work on Windows for paths defined in `templateDir` property of a codegen config
* Adds tests for template resource locator

The Maven plugin follows a different flow for template directory versus resource loaded templates. I'd tried reproducing the reported bug, but it seems I was only testing `templateDirectory` under git bash so the problems didn't arise. I've tested `templateDir` and `templateDirectory` under both Mac and Windows, both locally and in a private git repo using workflows for cross-platform checks. This should be good to go, but I'd like to have another set of eyes on it before merge.

cc @OpenAPITools/generator-core-team 

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

File: modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java [hunk 1]
```diff
@@ -444,10 +445,20 @@ public Builder withTemplateDir(String templateDir) {
                     uri = f.toURI();
                     this.templateDir =  Paths.get(uri).toAbsolutePath().normalize().toString();
                 } else {
-                    URL url = this.getClass().getClassLoader().getResource(templateDir);
+                    String cpDir;
+                    // HACK: this duplicates TemplateManager.getCPResourcePath a bit. We should probably move that function to core.
+                    if (!"/".equals(File.separator)) {
```
Comment (agilob) [inline modules/openapi-generator-core/src/main/java/org/openapitools/codegen/config/WorkflowSettings.java:450]: minor: can be '/' to compare char to char rather than casting string to char

**Comment by jimschubert** [comment]
@wing328 could you check out the maven unit and integration tests in this PR? 5cae18f
These will run consistently on Windows and non-Windows builds. Do you think we should move the spot check examples from Shippable to an integration test, so we can spot check file outputs and contents as well?

**Comment by jimschubert** [comment]
Previous commits on this branch failed, and it took me a while to figure out.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/root/.m2/repository/org/codehaus/groovy/groovy-all/2.4.8/groovy-all-2.4.8.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[ERROR] The following builds failed:
[ERROR] *  custom-template/pom.xml
[ERROR] *  custom-template-resource/pom.xml
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:3.2.1:run (integration-test) on project openapi-generator-maven-plugin: 2 builds failed. See console output above for details. -> [Help 1]
```

maven-invoker-plugin is resolving with groovy 2.4.8 in CI, but resolves locally for me to 3.0.5. I'm able to build in Java 8 and 11 locally because of the supported groovy version. I'm not sure why there's a difference in resolution between my local machine and CI, but I've verified that explicitly setting the groovy dependency on the plugin will affect the groovy version evaluating the scripts. This should allow CI to pass.

**Comment by jimschubert** [comment]
I can't get some of our CI to work with the `maven-invoker-plugin`. I've tested this in a triggered GitHub workflow in a private repo and verified this is fixed in Windows for Java 8 and 11.

image

Loading from resource is potentially still an issue in Windows, but I couldn't find any release version which supported Maven's `templateResourcePath` in Windows.

Once this is merged, I'll add the maven integration tests to the check supported versions script which runs only on master.

**Comment by jimschubert** [comment]
And `templateResourcePath` only appears broken in Windows when `File.separator` is Windows style. I'll need to dig into that a little more separately.

**Comment by DenisKnoepfle** [comment]
It looks good now and works for Windows. I confirmed it with the 5.0.0-beta3 release.
