### PR TITLE
[JAVA][Server] Fixed issue #1525: Fix model class field initializations (Regression since 3.3.1)

### LINKED ISSUE #1525: [JAVA][Server] Generated model classes are missing default values
##### Description

Certain java server model classes do not properly declare default values for certain fields. For example, here is the beginning of Pet.java from the samples directory (pulled from `undertow`, `vertx-async`, `vertx-rx`). Note the missing default value for the `id`, `name`, and `status` fields:

```
@JsonInclude(JsonInclude.Include.NON_NULL) 
public class Pet   {
  
  private Long id = ;
  private Category category = null;
  private String name = ;
  private List<String> photoUrls = new ArrayList<>();
  private List<Tag> tags = new ArrayList<>();


  public enum StatusEnum {
    AVAILABLE("available"),
    PENDING("pending"),
    SOLD("sold");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return value;
    }
  }

  private StatusEnum status = ;

  public Pet () {

  }
```

##### openapi-generator version

This appears to be a regression since 3.3.1.

Reproduced issue with openapi generator 3.3.1, 3.3.2, 3.3.3, and current master. 

Testing against 3.3.0 generates models with proper defaults.

##### OpenAPI declaration file content or url

Issue is reproducible with certain java server samples (`undertow`, `vertx-async`, `vertx-rx`) provided in this project for the versions mentioned above.

##### Command line used for generation

Generate models from existing sample servers to reproduce the problem:

`mvn clean ; ./bin/java-undertow-petstore-server.sh`
`mvn clean ; ./bin/java-vertx-async-petstore-server.sh`
`mvn clean ; ./bin/java-vertx-rx-petstore-server.sh`

### PR DESCRIPTION
**Pull request by ccozzolino**
Fixed issue #1525. Fix model class field initializations.

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.4.x`, `4.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixes #1525. Added proper initialization of model class fields to fix regression introduced in 3.3.1

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### CODE REVIEW

File: samples/server/petstore/undertow/src/main/java/org/openapitools/model/Pet.java [hunk 1]
```diff
@@ -21,11 +21,16 @@
...
+  
   private Category category = null;
-  private String name = null;
+  
+  private String name;
+  
   private List<String> photoUrls = new ArrayList<String>();
-  private List<Tag> tags = new ArrayList<Tag>();
+
+  private List<Tag> tags = null;
```
Comment (wing328) [inline samples/server/petstore/undertow/src/main/java/org/openapitools/model/Pet.java]: @ccozzolino thanks for fixing the regression. Should this be `new ArrayList<Tag>()` instead of null?

**Comment by ccozzolino** [comment]
@wing328 - can we merge?

**Comment by wing328** [comment]
@ccozzolino thanks for the contribution, which has been included in the 4.0.0-beta release: https://twitter.com/oas_generator/status/1079727020374806529.

Happy New Year and looking forward to more collaboration and contributions in 2019!
