### PR TITLE
[spring] reactive: fix Content-Type

### LINKED ISSUE #15995: [BUG] [Spring] Example Response populates Content-Type from Accept
##### Description

The default implementation of Interfaces (possibly limited to `library: spring-boot`) for `application/json` responses with a sample response creates code which will throw a 500 response with the following message: 

> Content-Type cannot contain wildcard type '*'`

When called with an Accept Header "\*/\*" (e.g. as called through a standard Browser)

##### openapi-generator version

Gradle Plugin 6.6.0

##### Generation Details

Any GET method with a sample `application/json` response, and the following Gradle options:
```
configOptions = [
            dateLibrary: 'java8',
            interfaceOnly: 'true',
            library: 'spring-boot',
            reactive: 'true',
            sourceFolder: 'java/main',
            useResponseEntity: 'false',
            useSpringBoot3: 'true',
            useTags: 'true',
            ]
```

##### Suggest a fix

Problem appears to be that the generated code is as follows:
```
Mono<Void> result = Mono.empty();
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"value\" : \"Hello " + name + "!\" }";
                result = ApiUtil.getExampleResponse(exchange, mediaType, exampleString);
                break;
            }
        }
```
Which accepts `*/*` as compatible with `application/json`, and passes `*/*` to the `ApiUtil.getExampleResponse`. The code for that method has
```
response.getHeaders().setContentType(mediaType);
```
Which attempts to set the Content-Type to the passed in `*/*` type, which is an invalid Content-Type and throws the above error.

While the check for compatibility with `application/json` seems correct, we should then pass `application/json` to be the correct Content-Type for the response.

### PR DESCRIPTION
**Pull request by martin-mfg**
fix #15995

Sets the content-type of responses to the actual type of the response,  not to whatever the client requested.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [x] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh
  ./bin/utils/export_docs_generators.sh
  ``` 
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (6.3.0) (minor release - breaking changes with fallbacks), `7.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request.
   @cachescrubber (2022/02) @welshm (2022/02) @MelleD (2022/02) @atextor (2022/02) @manedev79 (2022/02) @javisst (2022/02) @borsch (2022/02) @banlevente (2022/02) @Zomzog (2022/09)

### CODE REVIEW

File: samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/FakeApiDelegate.java [hunk 1]
```diff
@@ -88,7 +88,7 @@ default Mono<ResponseEntity<OuterComposite>> fakeOuterCompositeSerialize(Mono<Ou
         for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
             if (mediaType.isCompatibleWith(MediaType.valueOf("*/*"))) {
                 String exampleString = "{ \"my_string\" : \"my_string\", \"my_number\" : 0.8008281904610115, \"my_boolean\" : true }";
-                result = ApiUtil.getExampleResponse(exchange, mediaType, exampleString);
+                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("*/*"), exampleString);
```
Comment (borsch) [inline samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/FakeApiDelegate.java:91]: will this be converted to `application/json` under the hood?

Comment (martin-mfg) [reply samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/FakeApiDelegate.java]: Good catch 👍
I made some changes to also cover the case pointed out by you and more cases where media type was not set as expected.

**Comment by martin-mfg** [comment]
I added a new test endpoint which covers [the change in line 209](https://github.com/OpenAPITools/openapi-generator/pull/16228/files#diff-0a4dcb7a87a6da19a8abac9ea720f8a6bd6d88315ce989daad10f2d7354e44eaR209). This change wasn't invoked by any of the samples before.

**Review by borsch — APPROVED** [review]
