### PR TITLE
[cpp-pistache] removed model namespace when unused for operations

### LINKED ISSUE #637: [C++][Pistache-server] model is not a namespace-name
##### Description

The generator seems to add systematically the instruction _using namespace xxx::yyy::model ;_ without any needs and without, at least, one corresponding definition of the model namespace. The C++ compilation failed.

Compilation error looks like

```
In file included from api/CheckApi.cpp:13:0:
api/CheckApi.h:39:60: error: ‘model’ is not a namespace-name
 using namespace com::bcom::amf::microservice::server::ms1::model;
                                                            ^
api/CheckApi.h:39:65: error: expected namespace-name before ‘;’ token
 using namespace com::bcom::amf::microservice::server::ms1::model;
                                                                 ^
api/CheckApi.cpp:23:60: error: ‘model’ is not a namespace-name
 using namespace com::bcom::amf::microservice::server::ms1::model;
                                                            ^
api/CheckApi.cpp:23:65: error: expected namespace-name before ‘;’ token
 using namespace com::bcom::amf::microservice::server::ms1::model;
                                                                 ^
```

NOTE : The hierarchical namespace names shown above is mine but the bug issue is non dependent. Using the default namespaces will produce a similar compilation error.
If needed, you will find my config.json file content below

##### openapi-generator version

3.1.2-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Check unknown namespace-name model
servers:
  - url: http://localhost:8080
paths:
  /check:
    get:
      summary: blabla
      operationId: list
      tags:
        - Check
      responses:
        '200':
          description: Everythings gonna be alright
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Bytes"
      default:
        description: unexpected error
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Bytes"

components:
  schemas:
    Bytes:
      format: byte
      type: string

    Content:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/Bytes'
```

```json
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Check unknown namespace-name model"
  },
  "servers": [
    {
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/check": {
      "get": {
        "summary": "blabla",
        "operationId": "list",
        "tags": [
          "Check"
        ],
        "responses": {
          "200": {
            "description": "Everythings gonna be alright",
            "headers": {
              "x-next": {
                "description": "A link to the next page of responses",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Bytes"
                }
              }
            }
          }
        },
        "default": {
          "description": "unexpected error",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Bytes"
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Bytes": {
        "format": "byte",
        "type": "string"
      },
      "Content": {
        "type": "object",
        "properties": {
          "type": {
            "$ref": "#/components/schemas/Bytes"
          }
        }
      }
    }
  }
}
```

config.json :
```json
{
    "modelPackage"   : "com.bcom.amf.microservice.server.ms1.model",
    "apiPackage"     : "com.bcom.amf.microservice.server.ms1.api"
}

```
##### Command line used for generation
Generate :
```
openapi-generator-cli.sh generate -i ./openapi.yaml -g cpp-pistache-server -c ./config.json -o .
```

Compile :
```
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/api/CheckApi.o api/CheckApi.cpp
```

##### Steps to reproduce

Generate & compile

##### Related issues/PRs
N/A

##### Suggest a fix/enhancement

In case the generator needs to let this behavior as this, include systematically the ModelBase.h header file ... but I don't think its the best proposal ever seen :rofl: 
The generator should add the using namespace xxx::yyyy::model only when using, at least, one model class.

### PR DESCRIPTION
**Pull request by etherealjoy**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
When there is no import of any model header remove the usage of model namespace as well for each model.
No impact to samples after generation.
Fixes #637 fully.

@ravinikam @MartinDelille @stkrwork @fvarose

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java [hunk 1]
```diff
@@ -250,7 +250,7 @@ public CodegenOperation fromOperation(String path, String httpMethod, Operation
                 if(importMapping.containsKey(hdr)) {
                     continue;
                 }
-                additionalProperties.put("hasModelImport", true);
+                operations.put("hasModelImport", true);
```
Comment (stkrwork) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java]: wouldnt it better to put this in the vendor extensions?

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java]: We may consider adding this to the top level so that all generators can also use `hasModelImport` (I've seen another related request before)

Comment (wing328) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java]: @etherealjoy please go with vendor extension for the time being (e.g. x-codegen-pistache-hasModelImport)

Comment (etherealjoy) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CppPistacheServerCodegen.java]: @wing328 @stkrwork 
Ok, done using vendor extensions

**Comment by etherealjoy** [comment]
@wing328 @stkrwork
Ok vendor extension is only at operation level but not at API level. therefore we cannot use vendor extension.
I need to put the variable at `operations` level not at `operation` level.
The suggestion is not working unless we add vendor extension at operations level.

**Comment by etherealjoy** [comment]
@wing328 
`vendorExtensions` is a member of `CodegenOperation`, but `operations` in method
```java
private Map<String, Object> processOperations(CodegenConfig config, String tag, \
List<CodegenOperation> ops, List<Object> allModels)
```
is a `Map<String, Object>` and contains the member `hasImport` as well. 
```java
if (imports.size() > 0) {
     operations.put("hasImport", true);
}
```
So I think it makes sense to add `hasModelImport` here as well in the overriden method. `vendorExtensions` is only at `operation` level and is not working.
I reverted the change back to not use `vendorExtensions` and if you think it is OK we can merge and I have tested it.

**Comment by wing328** [comment]
@etherealjoy thanks for the detailed explanation. I'm ok with your suggested change.

We'll consider adding this to the default codegen later.
