### PR TITLE
[java] fix javadoc configuration

### LINKED ISSUE #3299: [BUG][okhttp-gson] can not generate javadoc
##### Description

Introduced with issue #2994 / PR #2995 the generated javadoc now contains `@http.response.details`. Example from our the samples:

https://github.com/OpenAPITools/openapi-generator/blob/51e7005373fdb55daa1c253f36fb6267a64a7bf7/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/StoreApi.java#L63-L68

When trying to generate the javadoc artifact for the project, you get tons of errors:

```
cd samples/client/petstore/java/okhttp-gson
mvn javadoc:javadoc
```

```
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.419 s
[INFO] Finished at: 2019-07-08T10:44:48+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:javadoc (default-cli) on project petstore-okhttp-gson: An error has occurred in JavaDocs report generation: 
[ERROR] Exit code: 1 - /____/openapi-generator/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java:63: error: unknown tag: http.response.details
[ERROR]      * @http.response.details
[ERROR]        ^
[ERROR] /____/openapi-generator/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java:117: error: unknown tag: http.response.details
[ERROR]      * @http.response.details
[ERROR]        ^
[ERROR] /____/openapi-generator/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/api/AnotherFakeApi.java:134: error: unknown tag: http.response.details
[ERROR]      * @http.response.details
[ERROR]        ^
```

##### openapi-generator version

4.0.2

##### Suggest a fix

We can keep the table, but remove the `@http.response.details` and just put "Response details:"

@saigiridhar21, @wing328 what do you think?

### PR DESCRIPTION
**Pull request by jmini**
Fixes #3299.

The special javadoc tag `@http.response.details` needs to be declared correctly, so that the javadoc can be built.

---

For maven, this PR changes where the `<configuration>` block is added.
It was inside the `<execution>` bloc, but the example in the documetation ([Configuring Custom Javadoc Tags](https://maven.apache.org/plugins/maven-javadoc-plugin/examples/tag-configuration.html)) adds it directly in the `<plugin>` bloc.

For gradle, the [javadoc](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Javadoc.html) page do not really mention the `tags` option, but 
[GRADLE-1563](https://issues.gradle.org/browse/GRADLE-1563) does. See also [this question](https://stackoverflow.com/a/35121736/91497) on stackoverflow.

### CODE REVIEW

File: CI/circle_parallel.sh [hunk 1]
```diff
@@ -12,6 +12,7 @@ if [ "$NODE_INDEX" = "1" ]; then
   #cp CI/pom.xml.circleci pom.xml
   java -version
   mvn --quiet verify -Psamples.circleci
+  mvn --quiet javadoc:javadoc -Psamples.circleci
```
Comment (jmini) [inline CI/circle_parallel.sh]: Discussed with @wing328 on Gitter, this is a way to check that Javadoc can be built

**Comment by Alex-e** [comment]
Not fixed for sbt. 

`error: unknown tag: http.response.details
[error]      * @http.response.details`
