### PR TITLE
[elm] Fix repetitive enum prefixes

### LINKED ISSUE #2759: [BUG] [Elm] elmPrefixCustomTypeVariants
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

```json
    "Answers": {
      "type": "object",
      "required": [
        "houseLiving",
        "liabilityLegalProtection",
        "pets"
      ],
      "properties": {
        "houseLiving": {
          "type": "string",
          "enum": [
            "RENTED",
            "OWN_HOUSE",
            "OWN_FLAT",
            "PARENTS_HOUSE",
            "SHARED_FLAT",
            "RENT_FREE"
          ]
        },
        "liabilityLegalProtection": {
          "type": "array",
          "items": { "type": "string", "enum": ["BUILDER", "LANDLORD"] }
        },
        "pets": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["DOG", "CAT", "HORSE", "AQUARIUM"]
          }
        }
      },
      "title": "Answers"
    }
```

```elm
type HouseLiving
    = HouseLivingRENTED
    | HouseLivingOWNHOUSE
    | HouseLivingOWNFLAT
    | HouseLivingPARENTSHOUSE
    | HouseLivingSHAREDFLAT
    | HouseLivingRENTFREE


type LiabilityLegalProtection
    = LiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionBUILDER
    | LiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionLANDLORD

type Pets
    = PetsPetsPetsPetsDOG
    | PetsPetsPetsPetsCAT
    | PetsPetsPetsPetsHORSE
    | PetsPetsPetsPetsAQUARIUM
```

The actual output for `LiabilityLegalProtection` and `Pets` should only add the prefix a single time.

##### openapi-generator version

v4.0.0-beta3

##### Command line used for generation

```shell
    docker run --rm \
                -v "$PWD:/local" \
                openapitools/openapi-generator-cli:${OPEN_API_VERSION} generate \
                    -i /local/swagger.json \
                    -o "/local/$SDK_DIR/$generator" \
                    -g "$generator" \
                    --invoker-package "crm" \
                    --additional-properties elmEnableCustomBasePaths=true \
                    --additional-properties elmPrefixCustomTypeVariants=true
```

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/blob/69ad9a9957fc0dca9dbd792cb9a6a3b6f5bf197c/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java#L696-L698

A fix would be to check if the prefix is already part of the value. This will work, but will not remove the root cause. It seems that certain cases leed to concatenating the prefix 4 times. In other cases it's working fine.

@eriktim What do you think?

### PR DESCRIPTION
**Pull request by eriktim**
Fixes #2759.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`~~, `3.4.x`, `4.0.x`~~. Default: `master`.
- [x] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

For arrays of enums, the elm prefix is added four times, instead of once.

cc @wing328

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java [hunk 1]
```diff
@@ -694,7 +694,10 @@ public void updateCodegenPropertyEnum(final CodegenProperty property) {
         }
         final String prefix = toEnumName(property);
         for (Map<String, Object> enumVar : enumVars) {
-            enumVar.put("name", prefix + enumVar.get("name"));
+            if (!enumVar.containsKey("_isPrefixed")) {
+                enumVar.put("name", prefix + enumVar.get("name"));
+                enumVar.put("_isPrefixed", true);
```
Comment (andys8) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java]: An idea for an alternative: Test if `enumVar.get("name")` already starts with `prefix`. I guess it needs also to be not equal to `prefix` to support prefixing `type MyType = MyType`. Would this actually work and make storing `_isPrefixed` obsolete?

Comment (eriktim) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java]: Thought of that as well, but I'd like to keep the prefix consistent.

Comment (andys8) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java]: Okay
