### PR TITLE
[golang] Fix Null pointer exception in toVarName

### LINKED ISSUE #373: [go-server] Null Pointer exception when request body schema is array
##### Description

When the body of a request is an array NPE occurs

```java
  Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:934)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:828)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:460)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:786)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:315)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:58)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.AbstractGoCodegen.toVarName(AbstractGoCodegen.java:148)
	at org.openapitools.codegen.languages.AbstractGoCodegen.toParamName(AbstractGoCodegen.java:181)
	at org.openapitools.codegen.DefaultCodegen.toArrayModelParamName(DefaultCodegen.java:760)
	at org.openapitools.codegen.DefaultCodegen.fromRequestBody(DefaultCodegen.java:4214)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:2198)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:902)
	... 5 more
```

##### openapi-generator version

`master`
##### OpenAPI declaration file content or url

```yaml
---
# This is a sample Swagger spec
 
swagger: "2.0"
info:
  description: Container Application Model Description
  version: 1.0.0
  title: ContainerApplication
  
host: localhost:32000
basePath: /api/v1.0
schemes:
- http

tags:  
- name: ApplicationEndpointTest
  x-displayName: "ApplicationEndpointTest"
  description: |
    "Test of endpoints "
    
paths:
  /default/EndpointTest: 
    post:
      tags:
      - ApplicationEndpointTest      
      description: "post a request"
      operationId: callEndpoint
      consumes:
      - application/json
      parameters:
      - name: "requestList"
        in: "body"
        description: "Requests to post"
        required: true
        schema:
          $ref: "#/definitions/listitems"
      responses:
        200:
          description: "Successful response"
        404:
          description: "The request was not successfully executed."
      
  
definitions:
  listitems : 
    description: "list of items"
    type: array
    items: 
      type: "string"
```
##### Command line used for generation

java -jar ~/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ./api.yaml -o ./gengo-server -g go-server

### PR DESCRIPTION
**Pull request by etherealjoy**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `3.1.x`, `4.0.x`. Default: `master`.
- [X] Copied the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix null pointer exception when the request body parameter is an array of primitives or maps.
Fixes #373 

@wing328 @antihax @bvwells

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java [hunk 1]
```diff
@@ -144,8 +144,12 @@ public String escapeReservedWord(String name) {
 
     @Override
     public String toVarName(String name) {
+    	
+    	if(name != null) {
+    		name = name.replaceAll("-", "_");
+    	}
         // replace - with _ e.g. created-at => created_at
-        name = sanitizeName(name.replaceAll("-", "_"));
+        name = sanitizeName(name);
```
Comment (macjohnny) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java]: will sanitizeName() always return a non-null object?

Comment (etherealjoy) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java]: @macjohnny `super` will always return non `null`. If `name` is `null` it will return `ERROR_UNKNOWN`
This is a different issue tracked here #376

Comment (macjohnny) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java]: ok, so then this should be fine

Comment (etherealjoy) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java]: I could update this.

**Comment by etherealjoy** [comment]
I tested the NPE from #373 and it is solved.
Also I tested a leading '_' and it is also as you described.

**Comment by antihax** [comment]
Sounds good, thanks!
