### PR TITLE
[Clojure] Handle both types of additional properties when getting type declaration

### LINKED ISSUE #18199: [BUG][CLOJURE] Clojure fails with java.lang.ClassCastException
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
  Expected: a Plaid client is produced

  Actual output:
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'ProfileGetResponse'.Please make sure that your schema is correct!
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:540)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1226)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:535)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class io.swagger.v3.oas.models.media.Schema (java.lang.Boolean is in module java.base of loader 'bootstrap'; io.swagger.v3.oas.models.media.Schema is in unnamed module of loader 'app')
        at org.openapitools.codegen.languages.ClojureClientCodegen.getTypeDeclaration(ClojureClientCodegen.java:174)
        at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:4130)
        at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:3931)
        at org.openapitools.codegen.DefaultCodegen.addParentContainer(DefaultCodegen.java:5838)
        at org.openapitools.codegen.DefaultCodegen.addAdditionPropertiesToCodeGenModel(DefaultCodegen.java:3722)
        at org.openapitools.codegen.DefaultCodegen.updateModelForObject(DefaultCodegen.java:2966)
        at org.openapitools.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:3188)
        at org.openapitools.codegen.languages.ClojureClientCodegen.fromModel(ClojureClientCodegen.java:205)
        at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1681)
        at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:535)
        ... 4 more
```

##### Description

The output is above and command to generate the output is below.

##### openapi-generator version

v7.4.0

##### OpenAPI declaration file content or url

[https://github.com/plaid/plaid-openapi/raw/master/2020-09-14.yml](https://github.com/plaid/plaid-openapi/raw/master/2020-09-14.yml)

##### Generation Details

`openapi-generator-cli generate -g clojure -i 2020-09-14.yml -o build/generated-clojure`

##### Steps to reproduce

1. Clone [plaid-openapi](https://github.com/plaid/plaid-openapi/tree/master)
2. Install OpenAPI Generator CLI v7.4.0
3. Run the above command (in "Generation Details")

##### Suggest a fix

from [ClojureClientCodegen.java#L174](https://github.com/OpenAPITools/openapi-generator/blob/1bfe800b9fdb74d31a41d7e7811ae1c3fbe7acd7/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java#L174):
```java
Schema inner = (Schema) p.getAdditionalProperties();
```
This always suggests that getAdditionalProperties always returns a Schema object when it can also return a Boolean. Extra handling for the types might be needed.

### PR DESCRIPTION
**Pull request by njerig**
Fixes #18199.

### PR checklist
 
- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [] Pull Request title clearly describes the work in the pull request and Pull Request description provides details about how to validate the work. Missing information here may result in delayed response from the community.
- [ ] Run the following to [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) and update samples:
  ```
  ./mvnw clean package 
  ./bin/generate-samples.sh ./bin/configs/*.yaml
  ./bin/utils/export_docs_generators.sh
  ``` 
  (For Windows users, please run the script in [Git BASH](https://gitforwindows.org/))
  Commit all changed files. 
  This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. 
  These must match the expectations made by your contribution. 
  You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. 
  IMPORTANT: Do **NOT** purge/delete any folders/files (e.g. tests) when regenerating the samples as manually written tests may be removed.
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master` (upcoming 7.1.0 minor release - breaking changes with fallbacks), `8.0.x` (breaking changes without fallbacks)
- [x] If your PR is targeting a particular programming language, @mention the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) members, so they are more likely to review the pull request. (No one in Clojure technical committee)

### CODE REVIEW

**Comment by wing328** [comment]
lgtm. thanks for the fix

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java [hunk 1]
```diff
@@ -171,9 +171,13 @@ public String getTypeDeclaration(Schema p) {
 
             return "(s/coll-of " + getTypeDeclaration(inner) + ")";
         } else if (ModelUtils.isMapSchema(p)) {
-            Schema inner = (Schema) p.getAdditionalProperties();
-
-            return "(s/map-of string? " + getTypeDeclaration(inner) + ")";
+            Object additionalProperties = p.getAdditionalProperties();
```
Comment (wing328) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ClojureClientCodegen.java:174]: i've filed https://github.com/OpenAPITools/openapi-generator/pull/18212 to rename the variable to just `ap` as the generator itself also has a property/field named "additionalProperties"

**Comment by wing328** [comment]
fyi. filed https://github.com/OpenAPITools/openapi-generator/pull/18212 to fix the issue in other generators as well.
