### PR TITLE
[typescript] Clean up modelPropertyNaming across generators 

### LINKED ISSUE #2976: [BUG][Typescript] Incorrect types generated due to case/naming differences
I have a schema, which types such as:
image

This generates a typescript interface like:
```typescript
/**
 * 
 * @export
 * @interface VDN
 */
export interface VDN {
    /**
     * 
     * @type {string}
     * @memberof VDN
     */
    vdnExtension?: string;
    /**
     * 
     * @type {string}
     * @memberof VDN
     */
    vdnName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof VDN
     */
    skills?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof VDN
     */
    acdEngineId?: number;
    /**
     * 
     * @type {number}
     * @memberof VDN
     */
    lobId?: number;
    /**
     * 
     * @type {string}
     * @memberof VDN
     */
    lobName?: string;
    /**
     * 
     * @type {string}
     * @memberof VDN
     */
    programId?: string;
}
```

The structure is technically correct, even the property names have been converted from snake-case to camelCase. However this is just for the type, when I actually use the generated client, the property names are same as the original, so really the converted property names in the response are all undefined. Am I doing something wrong?

Generator: `typescript-axios`
OpenAPI-Generator version: `0.0.11-4.0.0-beta3`

### PR DESCRIPTION
**Pull request by amakhrov**
Fixes #2976

**Summary**
- Generators without runtime models conversion use "original" property naming by default. It's still possible to change it via cli options - might be helpful when used together with customized templates. The cli option description has been modified to provide some more context.
- Generators with runtime conversion (typescript-fetch, typescript-node, typescript-reduxquery) keep using "camelCase"

**Implementation notes**
- I decoupled `toVarName` from `toParamName`. Former respects the `modelPropertyNaming`, while latter keeps always using camelCase.
- Refactoring: use an enum instead of string for `modelPropertyNaming`. It now better resembles `enumPropertyNaming`.
- No samples have changed. It's because `petstore.yaml` has all model vars defined in camelCase - which means `original` naming (new) is effectively the same as `camelCase` (old).

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09) @topce (2018/10) @akehir (2019/07) @petejohansonxo (2019/11)

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java [hunk 1]
```diff
@@ -274,39 +283,36 @@ public String modelFileFolder() {
...
     public String toParamName(String name) {
-        // sanitize name
         name = sanitizeName(name, "[^\\w$]");
 
         if ("_".equals(name)) {
             name = "_u";
         }
 
-        // if it's all uppper case, do nothing
-        if (name.matches("^[A-Z_]*$")) {
```
Comment (amakhrov) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java]: I carelessly removed this special case.
Please let me know if there is a particular reason to handle upper case differently from everything else!

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java [hunk 2]
```diff
@@ -274,39 +283,36 @@ public String modelFileFolder() {
...
     }
 
     @Override
     public String toVarName(String name) {
-        name = this.toParamName(name);
-        
-        // if the property name has any breaking characters such as :, ;, . etc.
-        // then wrap the name within single quotes.
-        // my:interface:property: string; => 'my:interface:property': string;
-        if (propertyHasBreakingCharacters(name)) {
```
Comment (amakhrov) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java]: this would never happen, because at this point `name` has been sanitized with even more restrictive rules

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java [hunk 3]
```diff
@@ -89,8 +89,6 @@ public void setNpmRepository(String npmRepository) {
     @Override
     public void processOpts() {
         super.processOpts();
-        additionalProperties.put("isOriginalModelPropertyNaming", getModelPropertyNaming().equals("original"));
-        additionalProperties.put("modelPropertyNaming", getModelPropertyNaming());
```
Comment (amakhrov) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptRxjsClientCodegen.java]: This was not used either in the class or in the mustache templates. Most likely - copy/paste from another generator with runtime conversion support (like typescript-fetch)

**Comment by wing328** [comment]
@amakhrov thanks for the PR, which has been included in the 4.3.0 release: https://twitter.com/oas_generator/status/1243455743937789952
