### PR TITLE
[bug][core] Copy all attributes (not properties) on composed schemas when flattening models

### LINKED ISSUE #6950: [BUG] Multi level inheritance (with discriminator declared) does not generate classes with inheritance
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Java classes are not generated with `extends` when the OpenAPI  definition declares `allOf' with a `$ref` to a model with a `discriminator` declared. This seems to be a regression.

##### openapi-generator version

5.0.0 - master

##### OpenAPI declaration file content or url
```yaml
swagger: 2.0

info:
  title: Test Command model generation
  description: Test Command model generation
  version: 1.0.0
definitions:
  PartyType:
    description: type
    type: string
    enum:
      - customer
      - contact

  CustomerType:
    description: type
    type: string
    enum:
      - person
      - organization

  Entity:
    type: object
    properties:
      id:
        type: string
        readOnly: true

  Party:
    allOf:
      - $ref: '#/definitions/Entity'
      - type: object
        discriminator: party_type
        required:
          - party_type
        properties:
          party_type:
            readOnly: true
            $ref: '#/definitions/PartyType'
          tax_id_number:
            type: string

  Contact:
    x-discriminator-value: contact
    allOf:
      - $ref: '#/definitions/Party'
      - type: object
        properties:
          first_name:
            type: string
          last_name:
            type: string
          suffix:
            type: string
          dob:
            type: string
            format: date

  Customer:
    x-discriminator-value: customer
    allOf:
      - $ref: '#/definitions/Party'
      - type: object
        discriminator: customer_type
        required:
          - customer_type
        properties:
          customer_type:
            readOnly: true
            $ref: '#/definitions/CustomerType'
          customer_num:
            type: string
          external_customer_num:
            type: string
  Person:
    x-discriminator-value: person
    allOf:
      - $ref: '#/definitions/Customer'
      - type: object
        properties:
          first_name:
            type: string
          last_name:
            type: string

  Organization:
    x-discriminator-value: organization
    allOf:
      - $ref: '#/definitions/Customer'
      - type: object
        required:
          - organization_name
        properties:
          organization_name:
            type: string

  ApiError:
    type: object
    required:
    - code
    - message
    properties:
      code:
        type: string
        readOnly: true
      message:
        type: string
        readOnly: true

parameters:

paths:
  /customers:
    get:
      consumes: []
      operationId: queryCustomers
      tags:
      - Customer
      summary: Get customers
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/ApiError'
        default:
          description: Unknown error.
          schema:
            $ref: '#/definitions/ApiError'
  /contacts:
    get:
      consumes: []
      operationId: queryContacts
      tags:
      - Contact
      summary: Get contact
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Contact'
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/ApiError'
        default:
          description: Unknown error.
          schema:
            $ref: '#/definitions/ApiError'
  /parties:
    get:
      consumes: []
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/Party'
        400:
          description: Bad request.
          schema:
            $ref: '#/definitions/ApiError'
        default:
          description: Unknown error.
          schema:
            $ref: '#/definitions/ApiError'
```

##### Command line used for generation

`java -jar openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i test.yaml --library jersey2`

##### Steps to reproduce

Use the OpenAPI definitions above to generate a java client.
It produces stand alone classes like:
- `public class Organization { ... }`
- `public class Person { ... }`
- `public class Contact { ... }`

I would expect at least the following classes to be generated with:
- `public class Organization extends Customer { ... }`
- `public class Person extends Customer { ... }`
- `public class Contact extends Party { ... }`

but there is no inheritance at all.

##### Related issues/PRs
- https://github.com/OpenAPITools/openapi-generator/issues/6815
- https://github.com/OpenAPITools/openapi-generator/pull/6901
- https://github.com/OpenAPITools/openapi-generator/pull/6849

##### Suggest a fix

I have not had a change to investigate.

### PR DESCRIPTION
**Pull request by jimschubert**
Fixes #6950 

The model flattening for composed schemas was not copying all attributes of the schema being flattened. This broke inheritance across composed schemas, which is a feature that is supported by the specification.

cc @OpenAPITools/generator-core-team 
cc @jeff9finger 

Example output showing proper inheritance using spec from #6950:

image

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) beforehand.
- [x] Run the shell script `./bin/generate-samples.sh`to update all Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit as it would merge with master. These must match the expectations made by your contribution. You may regenerate an individual generator by passing the relevant config(s) as an argument to the script, for example `./bin/generate-samples.sh bin/configs/java*`. For Windows users, please run the script in [Git BASH](https://gitforwindows.org/).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`
- [x] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

File: modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java [hunk 1]
```diff
@@ -627,6 +653,30 @@ private Schema modelFromProperty(OpenAPI openAPI, Schema object, String path) {
         model.setXml(xml);
         model.setRequired(object.getRequired());
         model.setNullable(object.getNullable());
+        model.setDiscriminator(object.getDiscriminator());
```
Comment (spacether) [inline modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java:656]: So I have some questions about how our code works here. Can you help answer them?
1. This copies the property from the inline schema into the extracted schema that we put into openapi component schemas, right?
So it sets the discriminator on this schema:
```
      - type: object
        discriminator: party_type
        required:
          - party_type
        properties:
          party_type:
            readOnly: true
            $ref: '#/definitions/PartyType'
          tax_id_number:
            type: string
```
Which is extracted and used to create the schema with the key `Party_allOf`, correct?
2. Is only one Party_allOf class made for each composed schema or is each inline schema extracted out into its own Party_allOf1, Party_allOf2 etc?

Comment (jimschubert) [reply modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java:656]: `Party_allOf` will be created once, then any properties it references will be flattened. Later, we "lookup" the transient `Party_allOf` by serializing and deserializing the structure as the key of a map, and the value as a name. This is how we basically deduplicate those dynamic structures and associate them all with a generated name. See `structureMapper` in this PR which I've updated to have determinate property order. As it was, Jackson would probably serializer in the same way maybe 99% of the time, but without explicitly sorting it'll follow the same rules as JSON where map properties are technically unordered.

**Comment by jimschubert** [comment]
This PR adds to some work done in #6153, which caused master CircleCI to break due to two new properties in a test yaml file and `type: object` added to generated code for those properties.

These are fixed by this PR, so I'll go ahead and merge. If any reviewers have concerns we can address in a follow up change.
